### ISSUE TITLE
Feedback da Release 1

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#115]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***concretizar o feedback da release 1*** para ***organizar melhor o trabalho da equipe***.

**Critérios de Aceitação** 
- Issues necessárias deverão ser abertas;
- Issues caso necessário deverão ser excluídas;

**Tarefas**
- [x] Listar todos os pontos ditos na Release 1;

- [x] Adaptar o escopo do produto;

- [ ] Adaptar o processo;

**Anotações**

Pontos positivos:
- Histórico de edição nos documentos
- Análise de viabilidade técnica: escolhas de tecnologias bem justificadas
- Artefatos com qualidade, boa visão de produto e protótipo top
- Identidade visual
- Pipeline está bom
- Issues bem escritas
- Comunicação nas issues
- Código de conduta

Pontos de melhoria:
- ~Canvas: não ficou claro como o projeto vai ser financiado, sustentado~ ATUALIZADO
- Métricas: não tão clara como serão medidos e como funcionam
   - ~BCP não está bem documentado: como será inserido no contexto do projeto e medido?~ Não será mais utilizado, porém a nova pontuação deve ser documentada
- ~Não faz sentido complexidade ciclomática para MDS~ Métrica de código retirada
- ~Ficou faltando a automatização do estilo de código~ REALIZADO
- ~Diminuição do escopo, escolher só um papel e fazer o ciclo completo (MVP), apenas um mês para trabalhar e o outro mês para melhorias~ REALIZADO
- O processo não está bem definido
- Poucas issues foram entregues na R1 e são algumas as possibilidades para tal problema:
   - Pouca produtividade da equipe
   - Issues muito grandes, que acabam não cabendo em apenas uma sprint
   - Equipe trabalhando em issues que não foram mapeadas de fato
   - Documentação das sprints não deixou muito claro o que ocorreu nelas, muitas vezes documentação atrasada, confusa ou sem análise das métricas.
- Realização de testes com usuário para validação do produto
- É possível entregar ao final da R2 90% de cobertura de testes no vue
- Priorizar para a próxima sprint a história de usuário mais importante e implementá-la (o que vai resolver o problema)
- Não priorizar issues que não agreguem valor!
- União da equipe, pois parece que são 2 equipes diferentes.

**Comment by shayanealcantara** [comment]
Add o que lembrava e conferi os pontos que o @LeoSilvaGomes anotou também (ele deixou o papel comigo)
