### ISSUE TITLE
Visualização do dashboard do usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#116]
**Descrição**
Eu, como ***usuário***, gostaria de ***ver informações gerais das minhas participações*** para ***situar minha atuação na comunidade da colheita colaborativa***.

**Depende de:**
#44 #73 

**Critérios de Aceitação** 
- A tela deve ser exibida apenas para usuários autenticados
- Para a visualização do calendário, deve-se capturar qual é o dia atual e mostrar 7 dias (o atual +6) para que a pessoa possa visualizar os eventos mais próximos

**Tarefas**
- [x] Utilizando o vue, capturar o dia atual e quais são os próximos 6 dias (necessário tomar cuidado se for no final do mês por exemplo, e com o fato de que meses possuem durações diferentes);
- [x] Criar a visualização do calendário por semana (Acesso apenas para usuários logados);
- [x] Criar a parte de "Projetos Inscritos" (seria realmente esse o vocabulário), com dados **estáticos**.

**Observações**

Embora no protótipo a visualização do calendário semanal esteja como "dashboard de voluntário" é também a mesma tela para proprietários, pois ele também teria que visualizar quais colheitas em sua propriedade estão se aproximando.

**Telas do protótipo a serem levadas em consideração**
![image](https://user-images.githubusercontent.com/20935369/66274744-0dee5500-e858-11e9-99c2-359aef1130b2.png)

**Comment by MarthaDs** [comment]
branch da issue e page de dashboard criada.

**Comment by MarthaDs** [comment]
Segue exemplo de sidebar em vue
https://lusaxweb.github.io/vuesax/components/sideBar.html#default

**Comment by KiSobral** [comment]
Inicialmente estamos pesquisando maneiras viáveis de se implementar a barra lateral do usuário :)

As opções encontradas até então variam entre components do Vue ou implementações customizadas com CSS.

**Comment by KiSobral** [comment]
Para se implementar um carousel sensível à toque dentro da nossa aplicação, foi levantada a solução do Vue-Carousel.

[Link da documentação](https://ssense.github.io/vue-carousel/)

**Comment by KiSobral** [comment]
Para suprir as necessidades dessa issue, vamos utilizar a dependência do Vuetify:
A documentação pode ser lida [aqui](https://vuetifyjs.com/pt-BR/getting-started/quick-start)

**Comment by KiSobral** [comment]
[Componente da barra lateral](https://vuetifyjs.com/pt-BR/components/navigation-drawers)
[Componente dos carousels](https://vuetifyjs.com/pt-BR/components/carousels)

**Comment by KiSobral** [comment]
O card inferior da tela será implementado por meio da mescla de dois componentes do [Vuetify](https://vuetifyjs.com/pt-BR/)         
O [v-card](https://vuetifyjs.com/pt-BR/components/cards) e o [v-window](https://vuetifyjs.com/pt-BR/components/windows)

**Comment by RenatoBrittoAraujo** [comment]
Foi adicionada a validação mencionada sobre as colheitas estarem dentro do intervalo [dia atual, dia atual + 6]

**Comment by KiSobral** [comment]
A tradução dos elementos foi feita e detalhes de estilização foram ajeitados.
              
A issue está pronta para ser fechada e a branch está pronta para dar merge com a develop.
