### ISSUE TITLE
Correção de erros de análise estática

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#119]
**observação importante**

O melhor caso seria realizar essa issue bem no inicio da sprint e ela ser logo aceita, para que não haja conflitos, já que ela vai mexer em muitos arquivos

**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***corrigir os erros de análise estática*** para ***que o código do projeto esteja seguindo os padrões definidos pela equipe***.

**Critérios de Aceitação** 
- A integração contínua deve estar passando no frontend e no backend;

**Tarefas**
- [x] Observar os erros apontados pelo flake8 no backend;
- [x] Corrigir os erros apontados pelo flake8 no backend;
- [x] Observar os erros apontados pelo eslint no frontend;
- [x] Corrigir os erros apontados pelo eslint no frontent;

**Comment by jps12** [comment]
Os erros apontados pelo eslint dentro do frontend já foram corrigidos e o pull request ja foi feito
