### ISSUE TITLE
Visualização de propriedades

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#120]
**Descrição**
Eu, como ***proprietário***, gostaria de ***visualizar minhas propriedades*** para ***que possa gerenciá-las***.

**Depende de:**
#68 

**Critérios de Aceitação**
- Deverá permitir a visualização de árvores e colheitas de acordo com a propriedade escolhida;
- Essa visualização deve ser permitida para usuários autenticados;
- A visualização deve estar de acordo com o protótipo de alta fidelidade;
- Deve haver ênfase em colheitas que ainda não foram realizadas;
- Funcionalidade testada;

**Tarefas**
- [x] Criação do endpoint que exibe todas as propriedades de um usuário, concatenando colheitas e árvores que a ela pertencem;
- [x] Criação da tela com visualização de colheitas no frontend;
- [x] Exibição dos dados do endpoint no frontend.
- [x] Realização de testes

**Telas do protótipo a serem levadas em consideração**

![image](https://user-images.githubusercontent.com/20935369/66274834-d7650a00-e858-11e9-8754-6d90ddd8fd2c.png)

**Comment by KiSobral** [comment]
O atual estado da visualização desta página esta desta forma:
![image](https://user-images.githubusercontent.com/43852963/68800933-c2d71700-0639-11ea-84e3-a03c80ef7c02.png)

Falta apenas receber e tratar a visualização dos dados vindos do back-end

**Comment by KiSobral** [comment]
Como ainda não existe um campo destinado para o nome das colheitas no backend, a visualização das colheitas segue com dados estáticos até a mudança da model

![image](https://user-images.githubusercontent.com/43852963/68977567-4bd78500-07d7-11ea-94ab-9cf05d693a4d.png)

**Comment by KiSobral** [comment]
Toda a visualização está pronta para ser entregue e os dados (disponíveis até o momento) estão sendo organizadas corretamente

**Comment by durvalcarvalho** [comment]
100% de cobertura nas novas funcionalidades :) 

![image](https://user-images.githubusercontent.com/31013187/69007940-5868f400-0923-11ea-8641-0c14609d9286.png)

![image](https://user-images.githubusercontent.com/31013187/69007947-79314980-0923-11ea-9239-fefcd9b3fa8b.png)
