### ISSUE TITLE
Configuração de variáveis de ambiente

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#121]
**Descrição**
Eu, como ***devops***, gostaria de ***configurar variáveis de ambiente*** para ***que os ambientes apresentem comportamento definido de acordo com elas***.

**Critérios de Aceitação** 
- Dados como usuário e senha de banco de dados não devem ser commitados e nem ficarem em claro;
- Deve ser verificado a possibilidade de separação de dependências a partir do tipo de ambiente (por exemplo, o requirements.txt inteiro precisa ser instalado em todos os ambientes? pode ser separado em tipos diferentes homologação, desenvolvimento etc? o mesmo pro package.json);
- Para o ambiente de homologação e desenvolvimento o modo DEBUG das aplicações deve ser utilizado;
- Os "allowed hosts" devem ser configurados de acordo com os ambiente também (localhost e 0.0.0.0 para ambiente de desenvolvimento, etc...)

**Tarefas**
- [x] Configurar variáveis do banco de dados em ambiente de desenvolvimento;
- [x] Configurar variáveis do banco de dados em ambiente de homologação;
- [x] Configurar variáveis do django em ambiente de desenvolvimento;
- [x] Configurar variáveis do django em ambiente de homologação;
- [x] Configurar variáveis do vue em ambiente de desenvolvimento;
- [x] Configurar variáveis do vue em ambiente de homologação;

**Comment by shayanealcantara** [comment]
Sobre o critério 2, por serem poucas mudanças no package.json nas etapas de homologação e desenvolvimento, foi mais viável continuar sem a separação das dependências.
