### ISSUE TITLE
Ajuste das rotas do backend

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#125]
**Descrição**
Eu, como ***devops***, gostaria de ***ajustar as rotas do backend*** para ***que possam ser acessadas com ou sem o / no final***. 

Exemplo: 
https://acacia-backend-staging-test.herokuapp.com/users/ ou 
https://acacia-backend-staging-test.herokuapp.com/users 
devem direcionar pra mesma rota

**Comment by durvalcarvalho** [comment]
Uma das maneiras de se fazer
https://stackoverflow.com/questions/15706489/redirect-to-named-url-pattern-directly-from-urls-py-in-django/34310388

**Comment by durvalcarvalho** [comment]
> Uma das maneiras de se fazer
> https://stackoverflow.com/questions/15706489/redirect-to-named-url-pattern-directly-from-urls-py-in-django/34310388

Essa maneira só funciona para requisições do tipo GET...

Os dados dos demais tipos de requisições não são redirecionados dessa maneira...
