### ISSUE TITLE
Problema nas informações salvas pela internacionalização no navegador

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#128]
**Descrição**

Eu, como ***usuário***, espero que quando eu ***deslogar*** as telas continuassem na mesma linguagem que estava configurada.

Eu, como ***usuário***, espero que quando eu ***logar*** a linguagem da telas sejam configurada de acordo com a linguagem padrão da conta.

**Critérios de Aceitação**
- [x] Quando deslogado, a linguagem configurada deve ser manter.
- [x] Quando logado, a linguagem das telas deve ser a mesma da linguagem padrão do usuário.
- [ ] Funcionalidade testada.

**Tarefas**
- [x] Analisar store.js em busca da em guardar a linguagem de forma correta.

**Comment by shayanealcantara** [comment]
Não houve a realização de testes pois o bug foi no tratado no front. 
@durvalcarvalho @RenatoBrittoAraujo por favor, lembrem de atualizar as tarefas na issue, como foi discutido na retrospectiva.
