### ISSUE TITLE
Correções da atualização do perfil do usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#129]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***corrigir problemas mapeados na atualização do perfil do usuário*** para ***que a funcionalidade funcione corretamente***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Deverá ter o campo ...;
- Deverá calcular/apresentar ...;
- Funcionalidade testada;

**Tarefas**
- [x] Realizar a validação de idade, para maiores de 14 anos;
- [ ] Verificar se o formulário da edição de conta é atualizado após o usuário salvar suas informações;
- [ ] Caso não esteja funcionando a tarefa passada, implementá-la;
- [ ] Corrigir o bootstrap, que não está renderizado corretamente

**Comment by durvalcarvalho** [comment]
A branch que irá resolver essa issue deverá sofrer merge com a branch #73 ou com a develop?

**Comment by jps12** [comment]
Essa issue vai ser resolvida na branch feature/73-update-user

**Comment by jps12** [comment]
Foi resolvida a validação de idade dentro do datetime.

**Comment by jps12** [comment]
Dificuldades encontradas:
- O evento de confirmar dentro do datetime não está sendo reconhecido. Esse evento é necessário para alterar a variável birthdate.
- Os dados estão sendo recebidos do backend mas está dando erros quando tentamos enviar para o backend de volta.
- A navbar da página ainda está sobre o titulo quando rolamos a página

**Comment by shayanealcantara** [comment]
Tranferir as tarefas dessa issue para a #73
