### ISSUE TITLE
Adicionar templates nas issues, pull requests e atas de reunião

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#13]
### Descrição:
Adicionar templates para padronizar a comunicação durante o projeto e seguir as diretrizes da comunidade de software.

### Critérios de aceitação:
- Pull Requestes, issues e atas de reunião devem seguir um template. 

### Tarefas:
- [x] Adicionar template de issue
- [x] Adicionar template de pull request
- [x] Adicionar atas de reunião

**Comment by fabiolamfleury** [comment]
Templates are available in: https://github.com/fga-eps-mds/2019.2-TimeBolinho/tree/master/.github
