### ISSUE TITLE
Enviar imagem do formulário para o backend

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#130]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***enviar uma foto de um formulário para o backend*** para ***que a troca de informação entre eles seja consistente***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- A foto deve ser armazenada no backend
- A foto deve ser exibida corretamente no frontend

**Tarefas**
- [x] Enviar de formulário do frontend uma imagem, para o backend;
- [x] Salvar imagem no backend;
- [x] Configurar backend para poder recuperar imagem por meio de requisição
- [x] Enviar requisição do frontend pedindo para resgatar imagem do backend;
- [x] Exibir no frontend imagem que foi enviada do backend;

**Comment by jps12** [comment]
Seria melhor somente criar o caminho front-back ou criar um componente em vue que recebe a foto e já manda para o backend. Assim como um componente para carregar a foto do back para o front?

**Comment by fabiolamfleury** [comment]
@jps12 pensei nas funcionalidades que precisam usar isso, tipo a do perfil do usuário e o cadastro de árvore. É em mais de um lugar que vai ser usado, então vai existir um campo específico pra isso (que se traduz em um componente do vue)

**Comment by fabiolamfleury** [comment]
@jps12 você colocou na outra branch que encontrou uma solução pra isso, poderia colocar aqui um código de exemplo de como funciona?

**Comment by jps12** [comment]
@fabiolamfleury Eu estou testando na branch 67. Ontem estava testando e so aparecia mensagem de erro ai hoje quando eu notei na minha pasta no back vi que a imagem estava la. O problema é que ontem foram feitos muitos testes e não lembro qual poderia ter enviado

**Comment by fabiolamfleury** [comment]
Corrigido por tabela durante a resolução da issue #67
