### ISSUE TITLE
Adicionar build na integração contínua

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#137]
**Descrição**
Eu, como ***devops***, gostaria de ***adicionar builds ao script de integração contínua*** para ***evitar problemas no deploy contínuo***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Build check em pull requests para as branches develop, release e master;

**Tarefas**
- [x] Adicionar workflow de build no github actions

**Comment by vitorcx** [comment]
@fabiolamfleury esse workflow "test.yml" da issue #143 tem algum proposito especifico? Pelo que vimos ele está igual ao job "test" no workflow "main.yml", com a diferença do upload pro codecov no final. Seria só pra manter um padrão na issue #137

**Comment by fabiolamfleury** [comment]
@vitorcx é igual msm
