### ISSUE TITLE
Ajustar deploy no backend em homologação

### ISSUE THREAD

**Issue by vitorcx** [fga-eps-mds/2019.2-Acacia#145]
**Descrição**

Eu, como ***devops***, gostaria de ***ajustar o deploy do backend em homologação*** para ***obter uma versão estável e funcional do backend em homologação***.

**Critérios de Aceitação**
- Pagina do admin funcional
- Demais apps funcionais

**Tarefas**
- [x] Realizar makemigrations, migrate e collectstatic no container a ser usado no deploy

**Comment by fabiolamfleury** [comment]
@vitorcx @shayanealcantara vou puxar da devel e criar uma versão 'estável' de migrações pra vocês trabalharem na issue com mais tranquilidade. (vou mandar o pr da issue #142 )

**Comment by shayanealcantara** [comment]
Vimos que para fazer as migrations no heroku não basta os comandos do django. O heroku tem um também, que vimos neste [link](https://medium.com/agatha-codes/9-straightforward-steps-for-deploying-your-django-app-with-heroku-82b952652fb4). 
Antes de achar este comando, deletamos o banco do heroku e não foi possível configurá-lo, por problemas desconhecidos até então. Recriamos também as migrations, na tentativa de verificar se o [erro](https://github.com/fga-eps-mds/2019.2-Acacia/issues/149#issuecomment-548541184) persistia.

**Comment by shayanealcantara** [comment]
Agora voltamos ao erro, porém conseguimos reestabeler comunicação com o postgres do heroku.

**Comment by shayanealcantara** [comment]
Foi possível realizar as migrações diretamente pelo bash do heroku, seguindo as orientações do link citado anteriormente.

**Comment by fabiolamfleury** [comment]
Maravilha :)
