### ISSUE TITLE
Substituição do toasted

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#153]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***substituir o toasted*** para ***melhorar a visualização de erros pro usuário***.

Exemplo: https://vuejsdevelopers.com/2018/08/27/vue-js-form-handling-vuelidate/

![image](https://user-images.githubusercontent.com/20935369/68075411-3e0d1300-fd86-11e9-92bf-a279152388cb.png)

**Critérios de Aceitação**
- Deverá ser possível identificar qual campo está sendo validado;
- Deverá usar o vuelidate;

**Tarefas**
- [x] Encontrar quais lugares usam o toasted;
- [x] realizar substituição

**Exemplo de código**

```javascript
import Vuelidate from "vuelidate";
Vue.config.productionTip = false;

Vue.use(Vuelidate);

```

**Comment by MarthaDs** [comment]
O vuetify tem um tipo de forms que utiliza o Vuelidate para validção de campos. A nossa sugestão é utilizarmos este para manter uma estilização mais agradável ao usuário. Existem algum impedimento para que não seja feita essa modificação ? @fabiolamfleury @shayanealcantara @vitorcx @LeoSilvaGomes @hugonxc @durvalcarvalho

**Comment by shayanealcantara** [comment]
> O vuetify tem um tipo de forms que utiliza o Vuelidate para validção de campos. A nossa sugestão é utilizarmos este para manter uma estilização mais agradável ao usuário. Existem algum impedimento para que não seja feita essa modificação ? @fabiolamfleury @shayanealcantara @vitorcx @LeoSilvaGomes @hugonxc @durvalcarvalho

Nenhum que eu consiga pensar agora, @MarthaDs sucesso!
