### ISSUE TITLE
Visualização da barra lateral do usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#154]
**Descrição**
Eu, como ***usuário***, gostaria de ***ver informações gerais das minhas participações*** para ***situar minha atuação na comunidade da colheita colaborativa***.

**Depende de:**
#44 #73 

**Critérios de Aceitação** 
- A tela deve ser exibida apenas para usuários autenticados
- Para a visualização do calendário, deve-se capturar qual é o dia atual e mostrar 7 dias (o atual +6) para que a pessoa possa visualizar os eventos mais próximos
- A barra lateral, com os botões deve ser implementada (Opções de lingua da aplicação também deve estar presente, já que foi implementado na sprint anterior #40);

**Tarefas**
- [x] Criar a barra lateral do usuário;

**Observações**

Embora no protótipo a visualização do calendário semanal esteja como "dashboard de voluntário" é também a mesma tela para proprietários, pois ele também teria que visualizar quais colheitas em sua propriedade estão se aproximando.

**Telas do protótipo a serem levadas em consideração**
![image](https://user-images.githubusercontent.com/20935369/66274379-70dded00-e854-11e9-9d1a-54da6111f6f6.png)

**Comment by fabiolamfleury** [comment]
A issue #116  tinha essa parte como uma tarefa, e ela foi quebrada

**Comment by KiSobral** [comment]
Após um enfoque maior no componente da barra lateral.
As funcionalidades dessa feature estão todas prontas e funcionais, com exceção do display de informações do usuário que dependem da issue #73
