### ISSUE TITLE
Documentação da sprint 9

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#160]
**Descrição**
Eu, como scrum master, gostaria de documentar a sprint 9 para acompanhar o projeto e a equipe.

**Critérios de Aceitação** 
- Deverá ter o planejamento, retrospectiva e revisão e análise do scrum master;
- Deverá apresentar dados dos indicadores e métricas da equipe(quadro de conhecimentos, burndown, burndown de riscos);

**Tarefas**
- [x] Documentar planejamento;
- [ ] Documentar revisão;
- [x] Documentar métricas;
- [x] Documentar retrospectiva;
- [ ] Documentar análise do scrum master

**Comment by shayanealcantara** [comment]
@MarthaDs @fabiolamfleury falta incluir a análise do SM e a review.

**Comment by MarthaDs** [comment]
> @MarthaDs @fabiolamfleury falta incluir a análise do SM e a review.

Feito
