### ISSUE TITLE
Party Hard 

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2019.2-Acacia#161]
## História de Usuário
Nós como estudantes **tiltados** queremos **playar HARD** para **não surtar** e **entregar a release 2**

## Descrição

Era uma vez, um lugar muito tóxico, que se chamava AGF (Automático Gerador de Frango). Várias pessoas **workando** hard fazendo issue em 30 horas por dia. Após um burnout, um grupo bem babadeira decidiu que era hora de **playar** hard.

### Pré Party

- [x] Planejamento do cronograma (7 de novembro ~ 8 de novembro)
- [x] Transparência da informação (7 de novembro ~ 8 de novembro)
- [x] Confirmação das pessoas envolvidas (7 de novembro ~ 8 de novembro)
- [x] Planejamento das fantasias (7 de novembro ~ 8 de novembro)
- [x] Planejamento das bebidas (7 de novembro ~ 8 de novembro)
- [x] Planejamento da locomoção (7 de novembro ~ 8 de novembro)
- [x] Planejamento da estadia (7 de novembro ~ 8 de novembro)
- [x] Planejamento da alimentação (7 de novembro ~ 8 de novembro)
- [x] Definição de Regras do Rolê (7 de novembro ~ 8 de novembro)

### Before Party

- [x] Locomoção para casa Hugo (8 de novembro, 17~18hrs)
- [x] Commitar andamento (fotos)
- [x] Alimentação (8 de novembro, 18~19hrs)
- [x] Consumo de alcool (8 de novembro, 18~19hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 18~19hrs)
- [x] Consumo de alcool (8 de novembro, 18~19hrs)
- [x] Revezamento do amigo pnc que não sabe beber (8 de novembro, 18~19hrs)
- [x] Consumo de alcool (8 de novembro, 18~19hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 18~19hrs)
- [x] Consumo de alcool (8 de novembro, 18~19hrs)
- [x] Locomoção para local da festa (metrô) (8 de novembro, 19~20hrs)
- [x] Fila fucking hard (min 40 minutos) (8 de novembro, 20~21hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 20~21hrs)

### During Party

- [x] PARTY HARD
- [x] Commitar andamento (fotos)
- [x] Leonardo dando PT (Partido dos Trabalhadores) (8 de novembro, 21~22hrs)
- [x] Commitar andamento (fotos)
- [x] Revezamento do amigo pnc que não sabe beber (LEO) (8 de novembro, 21~22hrs)
- [x] PLAY HARD (8 de novembro, 21~22hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 21~22hrs)
- [x] Revezamento do amigo pnc que não sabe beber (LEO) (8 de novembro, 22~23hrs)
- [x] PARTY HARD (8 de novembro, 22~23hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 22~23hrs)
- [x] Revezamento do amigo pnc que não sabe beber (LEO) (8 de novembro, 22~23hrs)
- [x] PLAY HARD (8 de novembro, 23~24hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 23~24hrs)
- [x] Revezamento do amigo pnc que não sabe beber (LEO) (8 de novembro, 23~24hrs)
- [x] Encontrar todo mundo (8 de novembro, 24~01hrs)
- [x] Commitar andamento (fotos) (8 de novembro, 01~02hrs)

### Efter Party

- [x] Locomoção voltar para a casa do Hugo (8 de novembro, ? hrs)
- [x] Commitar andamento (fotos)
- [x] Consumo de água 
- [x] Planejar a Indie Party
- [x] Commitar andamento (fotos)
- [x] Consumo de água 

### Review Party
- [x] Consumo de água
- [x] Commitar andamento (fotos)
- [x] Locomoção para a reunião de MDS
- [x] Consumo da doces
- [x] Commitar andamento (fotos)
- [x] Se arrumar para a indie party

### After Party(Hugo) - During Party (Indie Party)
- [x] Consumo de água
- [x] Locomoção para a reunião
- [x] Commits na Issue (Fotos)

## Lunch Party
- [ ] Casa do Hugo -> Feijoada e paraGod

## Localização

- Hugo Party    -> [Emopalooza](https://www.facebook.com/events/507399809838923/)
- Indie Party   -> Toinha Tênis Clubs
- Review Party  -> FGA (ITRAC)

**Comment by LeoSilvaGomes** [comment]
Regras do Rolê:
- Não alterar o número de vidas no mundo
- Não dar PT (menos o Leo)
- Não brigar com ninguém

**Comment by durvalcarvalho** [comment]
O planejamento do party foi concluido e documentado

![photo5053404997047396441](https://user-images.githubusercontent.com/31013187/68417844-eac80580-0175-11ea-9396-22b2f5c27f22.jpg)

**Comment by durvalcarvalho** [comment]
Detalhes sobre o valor de entrada da festa.

Obs: Quem for fantasiado paga menos

![photo5053042398728398905](https://user-images.githubusercontent.com/31013187/68420290-cc183d80-017a-11ea-9170-07b9d7a3e03c.jpg)

**Comment by durvalcarvalho** [comment]
Fantasia 1 - Fantasma do Comunismo

![9965af13-f17f-47ed-ab4c-4f0c5b38e698](https://user-images.githubusercontent.com/31013187/68434069-d6483500-0196-11ea-8062-ddfba1b0bb83.jpeg)

**Comment by KiSobral** [comment]
Para manter a rastreabilidade das informações que virão a surgir,
segue a [localização da before party](https://maps.google.com?q=Guar%C3%A1%20I%20QI%204%20Condom%C3%ADnio%20do%20Bloco%20T%20da%20QI%2004%20Guar%C3%A1%20I%20-%20Guar%C3%A1,%20Bras%C3%ADlia%20-%20DF,%2071010-012&ftid=0x935a3196e3f69fd9:0x2755a7d03fefc018&hl=pt-BR&gl=br)

**Comment by durvalcarvalho** [comment]
Fantasia 2 - Mickey de Chernobyl

![image](https://user-images.githubusercontent.com/31013187/68516687-73709f80-0263-11ea-9c76-a7f0a59b1334.png)

![photo5057842845020432492](https://user-images.githubusercontent.com/31013187/68516694-79ff1700-0263-11ea-9905-63d6e95fdddc.jpg)

**Comment by LeoSilvaGomes** [comment]
Fantasia 3 - A protagonista do ep A Testemunha da série Love Death and Robots

![blob_9dwx](https://user-images.githubusercontent.com/38738836/68519169-25ad6480-026e-11ea-996b-2e87e02e6f2d.jpg)
![photo5057842845020432503](https://user-images.githubusercontent.com/38738836/68519170-27772800-026e-11ea-9cfb-85437957a68f.jpg)

**Comment by LeoSilvaGomes** [comment]
Jogamos eu nunca! E jogamos quem não bebe, bebê...

**Comment by LeoSilvaGomes** [comment]
Tentar fechar um Corote já fechado, check

**Comment by durvalcarvalho** [comment]
> Jogamos eu nunca! E jogamos quem não bebe, bebê...

O pessoal se exaltou e estava errando de propósito para beber

**Comment by durvalcarvalho** [comment]
Fantasia 4 - Gato do musical Cats

![image](https://user-images.githubusercontent.com/31013187/68530651-f982f980-02e8-11ea-90e3-94ec16f7ea07.png)


![image](https://user-images.githubusercontent.com/31013187/68530629-baed3f00-02e8-11ea-9e79-5ff4b5635030.png)

**Comment by durvalcarvalho** [comment]
Fantasia 5 - Pirata

![image](https://user-images.githubusercontent.com/31013187/68530667-26371100-02e9-11ea-9c1d-d27723dd02c0.png)

**Comment by durvalcarvalho** [comment]
Expectativa: <MEME AQUI>
![image](https://user-images.githubusercontent.com/31013187/68530672-39e27780-02e9-11ea-955c-dd18e4e2d5d2.png)

Realidade: <MEME AQUI>
![image](https://user-images.githubusercontent.com/31013187/68530683-5383bf00-02e9-11ea-8ee1-e9fbcdb87ab4.png)

**Comment by durvalcarvalho** [comment]
Fantasia 6 - Bruxa

![image](https://user-images.githubusercontent.com/31013187/68530710-c42adb80-02e9-11ea-82e7-02480630efef.png)

**Comment by durvalcarvalho** [comment]
Pseudofantasia 1 - Steve Wonder Dormindo

![image](https://user-images.githubusercontent.com/31013187/68530810-bcb80200-02ea-11ea-89ec-81fc2f6247c8.png)

**Comment by durvalcarvalho** [comment]
Quando você percebe que não foi tão boa idéia chamar essa galera pro rolê

![image](https://user-images.githubusercontent.com/31013187/68530830-e83aec80-02ea-11ea-85e0-62ff22766ae9.png)

![image](https://user-images.githubusercontent.com/31013187/68530849-fe48ad00-02ea-11ea-960d-1bc97fe2f6d2.png)

**Comment by durvalcarvalho** [comment]
Pseudofantasia 2 - Estátua da Liberdade sem tocha

![image](https://user-images.githubusercontent.com/31013187/68530860-1d473f00-02eb-11ea-893e-c532b75ecc42.png)

**Comment by durvalcarvalho** [comment]
Pseudofantasia 3 - Snorlax dormindo

![image](https://user-images.githubusercontent.com/31013187/68530886-5384be80-02eb-11ea-878e-9f1f40e3a1eb.png)


![image](https://user-images.githubusercontent.com/31013187/68530882-45cf3900-02eb-11ea-92af-5be4d0b86214.png)

**Comment by durvalcarvalho** [comment]
Momento antes de alguém inventar molhar o pão na bananinha

![image](https://user-images.githubusercontent.com/31013187/68530930-c5f59e80-02eb-11ea-9f91-c811baf055a2.png)

**Comment by durvalcarvalho** [comment]
Leozin no porta malas

![image](https://user-images.githubusercontent.com/31013187/68530974-271d7200-02ec-11ea-99ff-2e07a1fe3732.png)

**Comment by durvalcarvalho** [comment]
Fotos embaçadas

![image](https://user-images.githubusercontent.com/31013187/68531001-6a77e080-02ec-11ea-8dc4-6ffce3efa617.png)

![image](https://user-images.githubusercontent.com/31013187/68531005-719eee80-02ec-11ea-9b80-cec709a13cfc.png)

![image](https://user-images.githubusercontent.com/31013187/68531006-75327580-02ec-11ea-8e0a-5c339538756c.png)

![image](https://user-images.githubusercontent.com/31013187/68531007-7cf21a00-02ec-11ea-9489-fbd884c2d718.png)

![image](https://user-images.githubusercontent.com/31013187/68531010-83809180-02ec-11ea-9507-d614d7e49a68.png)

**Comment by durvalcarvalho** [comment]
Pseudofantasia 4 - Joker Dançando

![image](https://user-images.githubusercontent.com/31013187/68531023-b6c32080-02ec-11ea-8ce3-99160d503dc6.png)

![image](https://user-images.githubusercontent.com/31013187/68531031-c80c2d00-02ec-11ea-8e1a-604c1e481229.png)

**Comment by durvalcarvalho** [comment]
Pseudofantasia 5 - Sasuke derrotado

![image](https://user-images.githubusercontent.com/31013187/68531085-5ed8e980-02ed-11ea-8389-aa3a88e305d4.png)

![image](https://user-images.githubusercontent.com/31013187/68531088-64ceca80-02ed-11ea-9ceb-b403c98c409e.png)

**Comment by durvalcarvalho** [comment]
Todos os membros em perfeito estado físico na reunião de sábado

![image](https://user-images.githubusercontent.com/31013187/68533898-31039d00-030d-11ea-9c7a-2f9b6ff4db69.png)

**Comment by durvalcarvalho** [comment]
Todos perfeitamente hidratados
![image](https://user-images.githubusercontent.com/31013187/68533926-8cce2600-030d-11ea-8b7b-2367331867e5.png)

**Comment by LeoSilvaGomes** [comment]
Indo para a indie party

![photo_2019-11-11_09-10-48](https://user-images.githubusercontent.com/38738836/68586438-67533080-0463-11ea-8bc0-3ada2c3c7a02.jpg)

Durante a indie party

![photo_2019-11-11_09-10-12](https://user-images.githubusercontent.com/38738836/68586456-6fab6b80-0463-11ea-8ccf-570f8f61e547.jpg)

PT da indie party

![photo_2019-11-11_09-10-26](https://user-images.githubusercontent.com/38738836/68586489-818d0e80-0463-11ea-8048-992f58bb8024.jpg)
