### ISSUE TITLE
Criar a Release 2

### ISSUE THREAD

**Issue by vitorcx** [fga-eps-mds/2019.2-Acacia#165]
**Descrição**
Eu, como ***devops***, gostaria de ***criar uma release*** para ***realizar uma entrega parcial do produto***.

**Critérios de Aceitação**
- Deverá resumir o trabalho realizado e entregue nas branches: master e gh-pages;

**Tarefas**
- [x] Criar release no github;
- [x] Criar lista explicando o que foi entregue;

**Comment by shayanealcantara** [comment]
Release 2 do repositório [2019.2-Acacia](https://github.com/fga-eps-mds/2019.2-Acacia) criada. Resta agora o do [front-end](https://github.com/fga-eps-mds/2019.2-Acacia-Frontend)
