### ISSUE TITLE
Evoluir o dashboard do usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#166]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***atualizar o dashboard do usuário*** para ***exibir informações da colheita que o usuário é proprietário***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Os dados devem mudar de estáticos para gerados a partir de backend;

**Tarefas**
- [ ] Fazer a requisição no backend das colheitas;
- [ ] Exibir corretamente

**Telas do protótipos**

![image](https://user-images.githubusercontent.com/20935369/66274825-b997a500-e858-11e9-8a13-ed326ade968c.png)

**Comment by KiSobral** [comment]
Para a evolução do Dashboard de usuário, será necessário a atualização da model de colheitas e do endpoint do cadastro de colheita, já que as models não possuem um atributo destinado para titulo

**Comment by shayanealcantara** [comment]
Devido a mudanças no fluxo #167, esta tela não será mais necessária. No lugar dela, será adaptada outra tela, com outras especificações #190
