### ISSUE TITLE
Verificar os fluxos de funcionamento da aplicação

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#167]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***verificar os fluxos de funcionamento da aplicação*** para ***assegurar que o usuário consegue navegar pela aplicação***.

**Critérios de Aceitação**
- Fluxo documentado
- Pequenos bugs resolvidos

**Tarefas**
- [x] Eles que lutem;
- [x] Identificar fluxos existentes
- [x] Identificar páginas ausentes
- [x] Identificar oportunidades de melhoria
- [x] Identificar bugs
- [x] Resolver pequenos bugs
- [x] Excluir fluxos inexistentes

**Comment by LeoSilvaGomes** [comment]
![photo_2019-11-13_11-52-13](https://user-images.githubusercontent.com/38738836/68774696-411cc480-060c-11ea-9c0c-f0ce20918cec.jpg)

Identificamos alguns fluxos que precisam ser refatorados para antes da R2, já que precisamos um MVP e ainda não temos. As setas vermelhas na imagem acima são os fluxos que identificamos que estão ausente na nossa aplicação. Muito deles é por pura usabilidade e elegância da plataforma Os asteriscos são onde o usuário irá inicializar na nossa plataforma:

- Deve haver duas páginas iniciais:
  - para usuário não logado: Landing Page
  - para usuário logado: Dashboard
- Ao terminar de cadastrar uma propriedade a pessoa deve ter a possibilidade de fazer a colheita diretamente ou retornar para o dashboard.
- A partir do meu perfil a pessoa deve ter a possibilidade de editar seu perfil.
- A partir do calendário a pessoa deve ter a possibilidade de cadastrar uma colheita ou uma propriedade.
- A partir do dashboard a pessoa deve ter a possibilidade de cadastrar e se inscrever em uma colheita.
- A partir do dashboard ao clicar em uma data a pessoa deve ser direcionada para o calendário para o dia já selecionado.

**Comment by LeoSilvaGomes** [comment]
Foi exclui o fluxo que até então estava mapeado, que era o Open Data, no qual irei mostrar gráficos e dados importantes para o usuário, mediante ao tempo, foi dropada essa funcionalidade

**Comment by LeoSilvaGomes** [comment]
No calendário o botão "plus", não tinha funcionalidade, por ser uma implementação fácil, foi adicionado para melhor compreensão dos fluxo que seriam seguidos posteriormente.

**Comment by shayanealcantara** [comment]
Os dados desta issue foram úteis para o planejamento e priorização das demandas da sprint 12.
