### ISSUE TITLE
Melhorias na navegabilidade da aplicação

### ISSUE THREAD

**Issue by vitorcx** [fga-eps-mds/2019.2-Acacia#174]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***implementar melhorias em pontos especificas da aplicação*** para ***tornar a navegação mais intuitiva***.

**Critérios de Aceitação**
- Dashboard redireciona para calendário no dia selecionado
- Botão no dashboard para criar uma colheita, com modal caso usuário não possua propriedade
- A partir do calendário deve ser possível se inscrever numa colheita, cadastrar uma colheita e cadastrar uma propriedade caso o usuário não possua uma  

**Tarefas**
- [x] Refatorar dashboard
- [x] Refatorar calendario

**Comment by fabiolamfleury** [comment]
Abriu várias outras issues e pr foi aceito no front
