### ISSUE TITLE
Preparar apresentação da Release 2

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#184]
**Descrição**
Eu, como ***time de projeto***, gostaria de ***preparar a apresentação para Release 2*** para ***compartilhar os resultados do projeto***.

**Critérios de Aceitação** 
- Apresentação em slides
- A apresentação deve ocupar no máximo 10 minutos
- A apresentação deve priorizar os resultados do produto

**Tarefas**

- [x] Elencar tópicos a serem explanados na apresentação

- [x] Criar roteiro da apresentação

- [x] Criar documento powerpoint para apresentação

**Comment by fabiolamfleury** [comment]
A professora @RochaCarla orientou durante a aula de EPS a focar nos pontos fortes da equipe durante a apresentação, tendo em vista que temos apenas 10 minutos para realizá-la e neste tempo é impossível explicar todos os aspectos de projeto/produto. Todos os membros devem estar aptos a explicar os diferentes aspectos da Acacia, e devemos tentar equilibrar a quantidade de EPS/MDS que apresentará.


Sugiro alguns tópicos para abordarmos:
- Parte de devops
- Parte de tecnologias
- Parte de produto

**Comment by fabiolamfleury** [comment]
@mds deve treinar para responder as perguntas da banca

**Comment by shayanealcantara** [comment]
Para equilibrar as pessoas de EPS e MDS na apresentação, foi decidido esses membros:
@fabiolamfleury @vitorcx @durvalcarvalho @LeoSilvaGomes e @KiSobral

**Comment by MarthaDs** [comment]
Foi feito um ensaio no dia 26/11 as 12:30 na FGA.
Estavam presente: @fabiolamfleury @shayanealcantara @MarthaDs @vitorcx @LeoSilvaGomes @KiSobral @durvalcarvalho

**Comment by fabiolamfleury** [comment]
Outro ensaio foi realizado 11:50 na FGA.
Estavam presentes apenas os membros que realizarão a apresentação: 
@fabiolamfleury @vitorcx @durvalcarvalho @LeoSilvaGomes e @KiSobral 

A apresentação foi disponibilizada para os professores e a preparação finalizada :)
