### ISSUE TITLE
Configuração do ambiente de homologação e produção do frontend

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#186]
**Descrição**
Eu, como ***devops***, gostaria de ***configurar o ambiente de produção do frontend*** para ***disponibilizar de forma estável o produto***.

Depende de: #80 

**Critérios de Aceitação**
- Deverá ser acessível no ip da máquina da DigitalOcean;
- Deverá estar se comunicando apenas com o backend de produção.

**Tarefas**
- [x] Resolver o erro 137;

**Observações**

- [x] Delimitar a treta

**Comment by vitorcx** [comment]
![image](https://user-images.githubusercontent.com/26859719/68998825-23fb2680-0896-11ea-8b6c-fff86d3d0007.png)

**Comment by shayanealcantara** [comment]
O problema 137 era relacionado a limite de memória RAM da máquina. Nossa máquina da Digital Ocean tinha capacidade de 1GB de RAM. Os containeres de homologação e produção ocupavam quase toda a capacidade. A solução foi alterar a capacidade da máquina provedora para 2GB.
![image](https://user-images.githubusercontent.com/33501171/69104019-c3125080-0a45-11ea-88de-046a8b046592.png)
