### ISSUE TITLE
Colocar a documentação na branch principal do projeto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#189]
**Descrição**
Eu, como ***como desenvolvedor***, gostaria de ***colocar a documentação na branch principal do projeto*** para ***alcance um objetivo***.

**Critérios de Aceitação** 
- Deverá ter cuidado para tirar da raíz a documentação (que fica no gh-pages) e colocar na pasta /docs;
- Deverá ter cuidado nas referências de imagem para a nova localização;

**Tarefas**
- [ ] Mudar o diretório da documentação ;
- [ ] Realizar pr da gh-pages para develop;

**Comment by shayanealcantara** [comment]
Branch para o github atualizada nas configurações para servir o diretório /docs.
