### ISSUE TITLE
Reoorganização dos slides do dashboard do usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#192]
**Descrição**
Eu, como ***usuário***, gostaria de ***visualizar minhas colheitas*** para ***informar quais colheitas ocorrerão***.

**Critérios de Aceitação**
- Utilizar os componentes já existentes;
- Deverá ter os campos preenchidos com a requisição do back;
- Ao clicar deve ser direcionado para a colheita;

**Tarefas**
- [x] Segundo slide colheitas da semana (JÁ ESTÁ IMPLEMENTADO, APENAS COLOCAR NA ORDEM);
- [x] Adicionar link em cada cartão de colheita para redirecionar para a página da colheita
- [x] Adicionar o slide de minhas colheitas;
- [x] Resgatar do backend todas as colheitas do proprietário;

**Comment by KiSobral** [comment]
O componente de visualização de colheitas foi reformulado para que a estilização fique mais agradável ao usuário.
Atualmente, o componente está da seguinte forma:

![image](https://user-images.githubusercontent.com/43852963/69173576-cc033080-0ade-11ea-9ceb-9b83723fa648.png)

**Comment by KiSobral** [comment]
Para fechar a issue, restam somente:
* a internacionalização do material criado
* reajustar os erros de guia de estilo do código
