### ISSUE TITLE
Definir ferramentas de testes

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#23]
### Descrição:
Eu, como desenvolvedor, quero definir as ferramentas de testes que deverão cumprir com o escopo do projeto, para melhor monitorar e controlar entregas.

### Critérios de aceitação:
- Definir as ferramentas que serão usadas no contexto do projeto. 
- As ferramentas devem ser de backend e frontend.

### Tarefas:
- [x] Fazer comparativo das prováveis ferramentas
- [x] Escolher as ferramentas
- [x] Definir folha de estilo
- [x] Documentar as escolhas

**Comment by vitorcx** [comment]
Encontrei um material interessante: [vue-testing-unit-vs-e2e](https://vuejsdevelopers.com/2019/04/01/vue-testing-unit-vs-e2e/)
Esse material conclui que o ideal é usar os dois tipos de teste, pois as vantagens de um cobrem as desvantagens de outro.
O que acham da ideia de realizar apenas testes e2e? Tendo em vista que são mais rápidos de se escrever e testam o funcionamento da aplicação **em geral**, interagindo com ela como se fosse um usuário real.
Posso estar errado, mas me parece ser positivo usar um tipo de teste onde gastaríamos menos tempo escrevendo(visto o prazo curto do projeto) e teríamos um retorno melhor em relação ao funcionamento da aplicação "**como um todo**", o que é mais valioso para o usuário, pois é assim que ele verá a aplicação.

**Comment by shayanealcantara** [comment]
Link que podem ser úteis para decisão:
- Back-end:
[Django rest testing](https://www.django-rest-framework.org/api-guide/testing/)
[Ferramentas de testes em Django - Parte 1](https://klauslaube.com.br/2011/07/18/ferramentas-de-testes-em-django-parte-1.html)
[Testando em django](https://django-portuguese.readthedocs.io/en/1.0/topics/testing.html)
[Getting started](https://realpython.com/python-testing/#choosing-a-test-runner)
Lembrar de recomendar o [Postman](https://www.getpostman.com/) 


- Front-end:
[Unit vs E2E Testing Vue.js](https://vuejsdevelopers.com/2019/04/01/vue-testing-unit-vs-e2e/)
[Jest](https://jestjs.io)
[Vue Test Utils](https://vue-test-utils.vuejs.org/)
[E2E - Cypress](https://www.cypress.io/)
[E2E - NIgthwatch](https://nightwatchjs.org/)
