### ISSUE TITLE
Criar ambiente de testes

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#25]
### Descrição:
Com as ferramentas definidas para o desenvolvimento de testes, o ambiente para este fim deve ser desenvolvido.

### Critérios de aceitação:
- O ambiente de testes deve estar estável para começar o desenvolvimento dos testes. 

### Tarefas:
- [ ] Criar ambiente de desenvolvimento de testes

**Comment by fabiolamfleury** [comment]
Essa issue foi resolvida junto com a #82
