### ISSUE TITLE
Documentar dailys da equipe

### ISSUE THREAD

**Issue by MarthaDs** [fga-eps-mds/2019.2-Acacia#29]
### Descrição:
Documentar todas as dailys da equipe, quem esteve presente, quando e onde foram feitas e comentar dificuldades muito pontuais.

### Critérios de aceitação:
- Deve conter nome dos participantes, horário, local  e nome dos faltantes

### Tarefas:
- [ ] Comentar as informações de cada daily na issue

**Comment by MarthaDs** [comment]
## Daily 1 
### Data/Hora: 02/09/2019 ás 22:30hrs.

### Participantes: @flaviovl @LeoSilvaGomes @RenatoBrittoAraujo @shayanealcantara @vitorcx @hugonxc 

### Faltantes: @durvalcarvalho @fabiolamfleury @jps12 

### Local: https://discord.gg/6UWY8Pj

Ob.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 2 
### Data/Hora: 03/09/2019 ás 22:10hrs.

### Participantes: @durvalcarvalho @fabiolamfleury @flaviovl @jps12 @MarthaDs @RenatoBrittoAraujo @vitorcx 

### Faltantes: @hugonxc @LeoSilvaGomes @shayanealcantara  

### Local: https://discord.gg/6UWY8Pj

Obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 3 
### Data/Hora: 04/09/2019 ás 22:10hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @RenatoBrittoAraujo @shayanealcantara @vitorcx @MarthaDs 

### Faltantes: @fabiolamfleury @hugonxc  

### Local: https://discord.gg/6UWY8Pj

Ob.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 4 
### Data/Hora: 05/09/2019 ás 13:30hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @RenatoBrittoAraujo @shayanealcantara @vitorcx @MarthaDs @fabiolamfleury

### Faltantes: @hugonxc  

### Local: Lappis FGA

obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 5 
### Data/Hora: 05/09/2019 ás 21:40hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @RenatoBrittoAraujo @shayanealcantara @vitorcx @MarthaDs @fabiolamfleury

### Faltantes: @hugonxc  

### Local: https://discord.gg/6UWY8Pj

obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 6 
### Data/Hora: 09/09/2019 ás 22:00hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @RenatoBrittoAraujo @shayanealcantara @vitorcx @MarthaDs @fabiolamfleury @hugonxc

### Faltantes:   

### Local: https://discord.gg/6UWY8Pj

obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 7
### Data/Hora: 10/09/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @RenatoBrittoAraujo @shayanealcantara @vitorcx  @fabiolamfleury @hugonxc

### Faltantes: @MarthaDs

### Local: Graminha FGA

obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 8
### Data/Hora: 11/09/2019 ás 22:00hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @shayanealcantara  @fabiolamfleury @hugonxc @MarthaDs @vitorcx

### Faltantes: @RenatoBrittoAraujo 

### Local: https://discord.gg/6UWY8Pj

obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 10
### Data/Hora: 17/09/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @flaviovl @jps12 @LeoSilvaGomes @shayanealcantara  @fabiolamfleury @hugonxc @MarthaDs @vitorcx @RenatoBrittoAraujo 

### Faltantes: 

### Local: Graminha FGA
obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 11
### Data/Hora: 18/09/2019 ás 12:20hrs.

### Participantes: @durvalcarvalho @jps12 @LeoSilvaGomes @shayanealcantara  @hugonxc @MarthaDs @vitorcx @RenatoBrittoAraujo 

### Faltantes: @fabiolamfleury @flaviovl 

### Local: ITRAC FGA
obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 12
### Data/Hora: 19/09/2019 ás 13:30hrs.

### Participantes: @durvalcarvalho @jps12 @LeoSilvaGomes @shayanealcantara  @hugonxc @MarthaDs @RenatoBrittoAraujo @fabiolamfleury @flaviovl 

### Faltantes:  @vitorcx 

### Local: Graminha FGA
obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 13
### Data/Hora: 24/09/2019 ás 22:00hrs.

### Participantes: @durvalcarvalho @jps12 @LeoSilvaGomes @shayanealcantara  @hugonxc @MarthaDs @flaviovl  @vitorcx

### Faltantes:  @fabiolamfleury @RenatoBrittoAraujo

### Local:  https://discord.gg/6UWY8Pj
obs.: Sem observações

**Comment by MarthaDs** [comment]
## Daily 14
### Data/Hora: 25/09/2019 ás 22:10hrs.

### Participantes: @durvalcarvalho @shayanealcantara  @hugonxc @MarthaDs @flaviovl  @vitorcx @LeoSilvaGomes 

### Faltantes:  @fabiolamfleury @RenatoBrittoAraujo @jps12 

### Local:  https://discord.gg/6UWY8Pj
obs.: Sem observações

**Comment by fabiolamfleury** [comment]
## Daily 15
### Data/Hora: 26/09/2019 ás 22:10hrs.

### Participantes: @durvalcarvalho   @hugonxc @fabiolamfleury @RenatoBrittoAraujo @vitorcx @LeoSilvaGomes 

### Faltantes: @shayanealcantara @jps12 @flaviovl  @MarthaDs

### Local:  https://discord.gg/6UWY8Pj
obs.: Sem observações

**Comment by fabiolamfleury** [comment]
## Daily 16
### Data/Hora: 01/10/2019 ás 13:15hrs.

### Participantes: @durvalcarvalho   @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl@LeoSilvaGomes 

### Faltantes:  @MarthaDs @vitorcx 

### Local:  LAPPIS

**Comment by shayanealcantara** [comment]
## Daily 17
### Data/Hora: 10/10/2019 ás 13:45hrs.

### Participantes: @durvalcarvalho   @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl@LeoSilvaGomes @vitorcx

### Faltantes:  @MarthaDs  

### Local:  Grama FGA

OBS.: Vitor participou remotamente pois não pode mais comparecer no horário.

**Comment by shayanealcantara** [comment]
## Daily 17
### Data/Hora: 07/10/2019 ás 13:00hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl@LeoSilvaGomes @MarthaDs @vitorcx

### Faltantes:    

### Local:  Lappis

**Comment by shayanealcantara** [comment]
## Daily 18
### Data/Hora: 10/10/2019 ás 13:45hrs.

### Participantes: @durvalcarvalho   @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl@LeoSilvaGomes @vitorcx

### Faltantes:  @MarthaDs  

### Local:  Grama FGA

OBS.: Vitor participou remotamente pois não pode mais comparecer no horário.

**Comment by shayanealcantara** [comment]
## Daily 19
### Data/Hora: 15/10/2019 ás 13:00hrs.

### Participantes: @durvalcarvalho   @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl@LeoSilvaGomes @MarthaDs @vitorcx

### Faltantes:    

### Local:  Grama FGA

**Comment by shayanealcantara** [comment]
## Daily 20
### Data/Hora: 17/10/2019 ás 13:15hrs.

### Participantes: @durvalcarvalho   @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl @MarthaDs @vitorcx

### Faltantes: @LeoSilvaGomes    

### Local:  Grama FGA

**Comment by shayanealcantara** [comment]
## Daily 21
### Data/Hora: 22/10/2019 ás 13:15hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @flaviovl@LeoSilvaGomes @MarthaDs @vitorcx

### Faltantes:   

### Local:  Grama FGA

OBS.: Vitor participou remotamente pois não pode mais comparecer no horário.

**Comment by shayanealcantara** [comment]
## Daily 22
### Data/Hora: 24/10/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @LeoSilvaGomes @vitorcx

### Faltantes: @MarthaDs @flaviovl

### Local:  Grama FGA

OBS.: Vitor participou remotamente pois não pode mais comparecer no horário.

**Comment by shayanealcantara** [comment]
## Daily 23
### Data/Hora: 29/10/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @RenatoBrittoAraujo  @shayanealcantara @jps12 @LeoSilvaGomes @vitorcx @MarthaDs @flaviovl

### Faltantes: 

### Local:  Grama FGA

OBS.: Vitor participou remotamente pois não pode mais comparecer no horário.

**Comment by shayanealcantara** [comment]
## Daily 24
### Data/Hora: 31/10/2019 ás 13:50hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @shayanealcantara  @LeoSilvaGomes @vitorcx 

### Faltantes: @RenatoBrittoAraujo @jps12 @MarthaDs @flaviovl

### Local:  Grama FGA

OBS.: Vitor participou remotamente pois não pode mais comparecer no horário.

**Comment by shayanealcantara** [comment]
## Daily 25
### Data/Hora: 05/11/2019 ás 13:45hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @shayanealcantara  @LeoSilvaGomes @RenatoBrittoAraujo @jps12 @flaviovl

### Faltantes: @MarthaDs @vitorcx 

### Local:  Grama FGA

**Comment by shayanealcantara** [comment]
## Daily 26
### Data/Hora: 07/11/2019 ás 13:45hrs.

### Participantes: @durvalcarvalho @KiSobral @fabiolamfleury @shayanealcantara  @LeoSilvaGomes @RenatoBrittoAraujo @vitorcx

### Faltantes: @MarthaDs  @jps12 @flaviovl

### Local:  Grama FGA

Obs: Vitor e Renato mandaram suas dailies de forma remota, por não poderem ir no horário (viagem e estágio)

**Comment by shayanealcantara** [comment]
## Daily 27
### Data/Hora: 12/11/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @KiSobral @LeoSilvaGomes @RenatoBrittoAraujo @vitorcx @jps12 @flaviovl 

### Faltantes: @fabiolamfleury @shayanealcantara @MarthaDs 

### Local:  Grama FGA

Obs: Vitor mandou suas daily de forma remota, por não poder ir no horário (estágio).

**Comment by vitorcx** [comment]
## Daily 28
### Data/Hora: 14/11/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @KiSobral @LeoSilvaGomes @RenatoBrittoAraujo @vitorcx @shayanealcantara  

### Faltantes: @fabiolamfleury @MarthaDs @jps12 @flaviovl 

### Local:  Grama FGA

**Comment by shayanealcantara** [comment]
## Daily 29
### Data/Hora: 19/11/2019 ás 13:40hrs.

### Participantes: @durvalcarvalho @KiSobral @LeoSilvaGomes @RenatoBrittoAraujo @vitorcx @jps12 @flaviovl @fabiolamfleury @shayanealcantara @MarthaDs 

### Faltantes: 

### Local:  UED FGA

Obs: Vitor mandou suas daily de forma remota, por não poder ir no horário (estágio).

**Comment by shayanealcantara** [comment]
## Daily 29
### Data/Hora: 21/11/2019 ás 13:40hrs.

### Participantes: @KiSobral @vitorcx @flaviovl @fabiolamfleury @shayanealcantara  

### Faltantes: @durvalcarvalho @LeoSilvaGomes @RenatoBrittoAraujo @jps12 @MarthaDs

### Local:  UED FGA

Obs: Vitor mandou suas daily de forma remota, por não poder ir no horário (estágio).

**Comment by MarthaDs** [comment]
## Daily 31
### Data/Hora: 26/11/2019 ás 12:30hrs.

### Participantes: @KiSobral @vitorcx  @fabiolamfleury @shayanealcantara @MarthaDs @durvalcarvalho @LeoSilvaGomes

### Faltantes: @jps12 @flaviovl  @RenatoBrittoAraujo

### Local:  FGA I-3
