### ISSUE TITLE
Gerenciar risco  da entrada de um novo membro

### ISSUE THREAD

**Issue by MarthaDs** [fga-eps-mds/2019.2-Acacia#30]
### Descrição:
Issue para documentar os treinamentos e estudos que estão sendo feito pelo novo membro @flaviovl 

### Critérios de aceitação:
 - [x] Documentar nessa issue os resultados dos treinamentos e estudos. 

### Tarefas:
Geral
- [x] Comentar o link dos repositorios com os resultados do treinamento de Git
- [x] Comentar o link dos repositorios com os resultados do treinamento de html/css
- [x] Comentar o link dos repositorios com os resultados do treinamento de metodos ageis
- [x] Comentar o link dos repositorios com os resultados do treinamento de docker
- [x] Comentar o link dos repositorios com os resultados do treinamento de python

**Comment by MarthaDs** [comment]
Treinamento realizado no dia 13/09.

Segue o link resultado desenvolvido durante o treinamento:
https://github.com/Treina-Bolinho/treinamento-GIT

**Comment by MarthaDs** [comment]
Treinamento realizado no dia 9/09.

Segue os links resultado desenvolvido durante o treinamento:
https://github.com/Treina-Bolinho/treinamento-python/tree/feature13-roll-dice
https://github.com/Treina-Bolinho/treinamento-python/tree/develop

**Comment by flaviovl** [comment]
Treinamento de Métodos Ageis
https://github.com/Treina-Bolinho/treinamento-metodos-ageis/tree/develop

**Comment by flaviovl** [comment]
Treinamento básico de HTML e CSS
https://github.com/Treina-Bolinho/treinamento-HTML-CSS/tree/develop

**Comment by MarthaDs** [comment]
Treinamento de Scrum foi substituido por um estudo e um teste a cerca da metodologia
https://github.com/Treina-Bolinho/treinamento-metodos-ageis/blob/develop/Questionario.md

**Comment by MarthaDs** [comment]
Treinamento de docker foi considerado o treinamento ministrado no dia 20/09, realizado no Lappis - FGA das 12hrs às 14hrs
