### ISSUE TITLE
Treinamento em Vue

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#36]
### Descrição:
Eu, como gerente do projeto, quero treinar os desenvolvedores, para capacitá-los em desenvolvimento frontend usando Vue. 

### Critérios de aceitação:
- Deverá ser apresentado um projeto introdutório com as funcionalidades básicas que o framework oferece.

### Tarefas:
- [x] Arranjar uma pessoa capacitada a dar o treinamento
- [x] Realizar o treinamento

**Comment by RenatoBrittoAraujo** [comment]
https://youtu.be/Wy9q22isx3U Tutorial rápido e interessante pra aprende vue. Completinho o suficiente pra quem tá iniciando.

**Comment by RenatoBrittoAraujo** [comment]
https://vuejs.org/v2/style-guide/ Style guide pro Vue, interessante a leitura

**Comment by shayanealcantara** [comment]
Treinamento irá ocorrer hoje (18/09) e será ministrado por um aluno da fga voluntário :smiley:

**Comment by shayanealcantara** [comment]
Treinamento finalizado com sucesso das 12:30 às 13:50. 
Funcionalidades vistas: 
- Sintaxe básica;
- Componentes;
- Rotas e seu gerenciamento;
- entre outras.
