### ISSUE TITLE
Elaborar documento de arquitetura

### ISSUE THREAD

**Issue by vitorcx** [fga-eps-mds/2019.2-Acacia#37]
### Descrição:
Documentar funcionamento da arquitetura de software que será utilizada no projeto.

### Critérios de aceitação:
- Visão geral da arquitetura documentada no github pages

### Tarefas:
- [x]  Descrição do funcionamento da arquitetura do Vue js
- [x]  Descrição do funcionamento da arquitetura do Django REST
- [x]  Descrição da comunicação entre o Vue js e o Django REST
- [x]  Diagrama de classes
- [x]  Diagrama de pacotes
- [x]  Diagrama de banco de dados
- [x]  Diagrama de caso de uso

### Pareamentos:
* Diagrama de Caso de Uso - Flávio e Leonardo
* Diagrama de Pacote - Durval e João
* Diagrama de Classes - Hugo e Renato
* Modelo Relacional Banco - Flávio e João

**Comment by RenatoBrittoAraujo** [comment]
Galera como é nossa primeira vez lidando com um documento de arquitetura, vocês podem linkar ou dar algum ideia de documentos de arquitetura do mesmo estilo do que nos vamos produzir para a gente poder dar uma olhada e entender o escopo da tarefa?

**Comment by shayanealcantara** [comment]
@RenatoBrittoAraujo Irei montar uma estrutura do documento e assim que terminar notifico vocês.

**Comment by RenatoBrittoAraujo** [comment]
Sobre o diagrama de classes, eu dei uma lida em vários documentos de arquitetura de semestre passados mas não consegui encontrar nenhum diagrama de classes. Nós vamos fazer algo novo ou eu procurei errado? Por diagrama de classes vocês dizem um UML?

**Comment by shayanealcantara** [comment]
> Sobre o diagrama de classes, eu dei uma lida em vários documentos de arquitetura de semestre passados mas não consegui encontrar nenhum diagrama de classes. Nós vamos fazer algo novo ou eu procurei errado? Por diagrama de classes vocês dizem um UML?

Sim, @RenatoBrittoAraujo, o diagrama UML é uma das abordagens de representar a arquitetura de software orientada a objetos.

**Comment by shayanealcantara** [comment]
Subi a estrutura do documento na branch desta issue.

**Comment by durvalcarvalho** [comment]
@fabiolamfleury você acha que seria interessante para o nosso projeto ter uma entidade 'Árvore'? Onde os proprietários teriam que especificar o tipo de árvore em sua propriedade antes de criar um evento colheita.

Eu estive sobre não especificar esse tipo de informação e deixar para o proprietário um campo de descrição onde ele iria dizer detalhes sobre o evento... Mas desse maneira seria complicado de na página sobre os dados projeto' dar detalhes sobre as colheitas que foram realizadas...

Qual sua visão sobre isso?

**Comment by fabiolamfleury** [comment]
Sim, com certeza! Pensando no saskatoon, eles tem até um certo 'banco de dados' de tipos de árvores (não precisamos criar isso, será criado por usuários e aumentando aos poucos. Alguns dados das árvores que seriam interessantes: espécie, qual época do ano é a época de colheita (ou se tem mais de uma vez no ano que dá frutos). É importante talvez também criar a noção de "Propriedade" pois aquela pessoa pode ter mais de uma arvore, do mesmo fruto ou de frutos diferentes

**Comment by durvalcarvalho** [comment]
Eu gostaria que você desse uma olhada na versão 0.1 do diagramas e modelos do banco de dados.

[bancos-saskatoon.pdf](https://github.com/fga-eps-mds/2019.2-TimeBolinho/files/3597238/bancos-saskatoon.pdf)

![saskatoon_conceitual](https://user-images.githubusercontent.com/31013187/64640808-272eed80-d3e1-11e9-839e-49d06ce33a6c.png)

Surgiu algumas dúvidas sobre alguns campos das entidades Voluntário, Beneficiário e Proprietário. 
* Esses são usuários da nossa aplicação? (Possuem login e senha)
* Fora os campos de identificação (nome, email), quais outras informações seriam interessante ter armazenado no banco de dados?

**Comment by vitorcx** [comment]
@durvalcarvalho Dei uma olhada no modelo, ficou muito bom, não consigo pensar em alguma necessidade ajuste por agora. Em relação às dúvidas, acredito que esses sejam sim os nossos usuários. Chegou a considerar algum ponto positivo ou negativo em adicionar o cpf ao usuário?

**Comment by durvalcarvalho** [comment]
Minha dúvida é sobre o beneficiário, ele terá uma conta no site? Se sim ainda não ficou claro quais seriam as ações dele dentro do site.

Outra questão é existe algum dado que precisamos coletar dos proprietários? Alguma informação que somente esse tipo de usuário tenha que informar? A mesma coisa a respeito do beneficiário.

Sobre o CPF, é comentado no site do Les Fruits Defendus, que crianças podem participar também, e não são todas as crianças que possuem CPF. Eu ainda não pensei sobre as chaves primárias de cada uma dessas entidades. E também não sei se esse contexto das crianças se aplicam ao nosso projeto...

Outras dúvidas que surgiram:

* [ ] Quais dados da propriedades precisamos ter armazenado? Fora o endereço e algumas fotos, existe algum dado importante que passou em branco?

* [ ] No contexto da Les Fruits Defendus, uma colheita poderia ser divida entre os proprietários, os voluntários e os beneficiários. Como essa relação poderia ser descrita no banco de dados? Essa relação se aplica ao nosso projeto?

**Comment by fabiolamfleury** [comment]
O que vocês de MDS acham? Existe essa necessidade de cadastrar o beneficiário? Ele diria quais são os tipos de doações que ele gostaria de receber? Talvez criar essa conta colocaria um obstáculo a mais na doação.

Quanto ao proprietário, acredito que para o usuário é interessante colocar data de nascimento, mas em específico para proprietário não consigo pensar em mais nada, além da marcação dele ser ou não proprietário.

**Comment by RenatoBrittoAraujo** [comment]
Acho que seria interessante existir uma página onde líderes/proprietários possam ver beneficiários, com dados sobre contato e como entregar doações. Porém, a questão dos beneficiários é como alguma instituição consegue se candidatar e ser adicionada ao site, e uma pessoa maliciosa tentando fazer o mesmo não consiga, mas sem intervenção direta de algum administrador que faz a validação de beneficiários?

Sobre o proprietário (e propriedades) vou procurar no saskatoon original ver se acho os campos que deviam ser preenchidos pra ver se o diagrama do @durvalcarvalho ta faltando algo.

Sobre os voluntários, acho muito válido essa solução.

No saskatoon, a página de colheita tem uma barra horizontal que indica quanto de cada colheita fica com o owner, voluntários e doação.

**Comment by RenatoBrittoAraujo** [comment]
## Sobre o diagrama de casos de uso
<img src="https://user-images.githubusercontent.com/45462822/64742168-a26fcc80-d4d1-11e9-98c8-e8e4dd406310.png"  style="display: block;margin: 0 auto;" alt="">


Alguém pode me dar um feedback à respeito desse diagrama? 

Ele atende todos os casos de uso? 

Algo pode ser melhorado?

**Comment by shayanealcantara** [comment]
@RenatoBrittoAraujo 
Essa é a notação usada nos casos de uso.
<img src="https://user-images.githubusercontent.com/33501171/64744320-aef82300-d4d9-11e9-857f-d7c4489a19f8.png" width="400"> 

- Os atores ficam sempre fora da fronteira, então você pode retirar esse retângulo externo a eles.
- Os casos de uso estão bem escritos.
- Verificar a necessidade de abranger casos de uso que sejam dependentes de outros ou opcionais na aplicação.  
- Não esquecer de fazer uma rápida e resumida priorização dos requisitos que o diagrama expõe.
- Fiquei um pouco confusa com a questão das setas entre os atores. Elas informam a herança em relação aos atores e casos de uso? 

Com uma conversa com a PO para alinhamento, alguns casos de uso, a princípio podem ser adicionados, como ilustra o screenshot:
<img src="https://user-images.githubusercontent.com/33501171/64747398-4ca51f80-d4e5-11e9-8a25-b5abc6280ac2.png" width="400">

**Comment by RenatoBrittoAraujo** [comment]
Eu procurei tentar incluir relação de extend ou include mas não consegui encontrar onde seria válido. Amanhã durante a reunião podemos conversar mais à respeito disso.

Sem as setas de herança o diagrama fica bem poluído, então achei por bom adicionar elas. Posso refazer sem elas se achar por melhor. Posso também adicionar algum indicador que são setas de herança.

Vou adicionar o caso de uso extra, remover o retângulo e o caso de uso de adicionar o líder e consertar notação.

Nota adicional: fiquei confuso, como é selecionado o líder da colheita?

**Comment by shayanealcantara** [comment]
> Alguém pode me dar algum feedback dos diagramas de pacotes que commitei?

@RenatoBrittoAraujo, sobre o diagrama de pacotes do back-end, não me parece completa a 1 versão, mas não tem problema, é um diagrama novo mesmo, vamos resolver isso :) Normalmente colocamos os diretórios mais relevantes da aplicação para representar a estrutura e as dependências entre eles. 
Os diretórios mais relevantes podem ser vistos quando criamos um projeto em Django-Rest, se isto for facilitar. Se você notar, as ações se concentram bastante nas views, urls, models, entre outras. Fiz um diagrama de outra matéria e acho que vocês podem aproveitar.
<Img src="https://user-images.githubusercontent.com/33501171/64834803-d9211200-d5b9-11e9-9907-26c93266235a.png" width="400">

**Comment by flaviovl** [comment]
![0 1_diagrama_de_classes](https://user-images.githubusercontent.com/31935777/64862152-2cba4c80-d608-11e9-9b85-8b9456b5534a.png)

**Comment by flaviovl** [comment]
Fiz um rascunho inicial do diagrama de classes, mas buguei bastante. Eu gostaria que você desse uma olhada.

**Comment by RenatoBrittoAraujo** [comment]
@shayanealcantara Dei uma olhada mais a fundo, e descobri que os geralmente os projetos em Django REST usam esse modelo:
```
- /project_root
--/apps
---/app1
----/api
-----/serializers.py
-----/viewsets.py
----/models.py
----/admin.py
---/app2
----/api
...
```
Que se traduziria nesse diagrama de pacotes:

![back_end_diagra](https://user-images.githubusercontent.com/45462822/64872015-c55ac780-d61c-11e9-90af-f77668dd10f6.png)

O que você acha sobre esse?

**Comment by shayanealcantara** [comment]
> O que você acha sobre esse?
Acho que ele não deixa muito claro a relação entre os pacotes

**Comment by RenatoBrittoAraujo** [comment]
![back_end_diagra (1)](https://user-images.githubusercontent.com/45462822/64874375-4451ff00-d621-11e9-8a74-ef5e73d58789.png)

Eu não se consigo deixar a estrutura de pastas mais estruturada que isso. A estruturação geralmente usada no django é simples e as dependências entre apps são relações bem Ad Hoc.

**Comment by fabiolamfleury** [comment]
A issue foi atualizada com os paramentos para sprint 3 e também foram desmarcados os diagramas, já que eles precisam ser revisados

**Comment by fabiolamfleury** [comment]
## Diagrama de caso de uso

Pontos de melhoria:

- Não tem o caso de uso de autenticação

- Não tem o uso de tornar um usuário líder de colheita (que deve ser executado tanto por um líder de colheita quanto por um usuário admin)

- Não existem as relações entre os casos de uso que deveriam existir (imagens meramente ilustrativas, vocês devem pensar no tipo de relação (se é include, extend, generalização ou associação) de cada caso de uso. Mas é importante pensar que: pra criar uma colheita, o proprietário deve estar logado, ter cadastrado uma propriedade, ter cadastro de árvore. Pra selecionar voluntários, a colheita já deve ter sido criada, e assim vai...

![image](https://user-images.githubusercontent.com/20935369/64913700-2cf73c80-d71b-11e9-86f5-1a017c7f4a4e.png)

**Comment by durvalcarvalho** [comment]
![diagrama_de_pacotes](https://user-images.githubusercontent.com/31013187/64923773-a478aa80-d7b3-11e9-996d-d5c06a7b9dc9.png)

@shayanealcantara  @vitorcx @fabiolamfleury 

Eu mudei o estilo do diagrama de pacotes para ficar parecido com uma árvore. Eu gostaria de saber se essa mudança é válida e se os componentes desse diagrama de acordo com a futura estrutura do nosso projeto.

**Comment by LeoSilvaGomes** [comment]
> ## Diagrama de caso de uso
> Pontos de melhoria:
> 
> * Não tem o caso de uso de autenticação
> * Não tem o uso de tornar um usuário líder de colheita (que deve ser executado tanto por um líder de colheita quanto por um usuário admin)
> * Não existem as relações entre os casos de uso que deveriam existir (imagens meramente ilustrativas, vocês devem pensar no tipo de relação (se é include, extend, generalização ou associação) de cada caso de uso. Mas é importante pensar que: pra criar uma colheita, o proprietário deve estar logado, ter cadastrado uma propriedade, ter cadastro de árvore. Pra selecionar voluntários, a colheita já deve ter sido criada, e assim vai...
> 
> ![image](https://user-images.githubusercontent.com/20935369/64913700-2cf73c80-d71b-11e9-86f5-1a017c7f4a4e.png)


![Untitled Diagram (1)](https://user-images.githubusercontent.com/38738836/64985344-0829d300-d89b-11e9-9bd3-8b2abd341bdf.png)

@shayanealcantara  @fabiolamfleury 

Fizemos as alterações solicitadas, mudando o estilo do diagrama e colocando as relações. Entretanto uma coisa pedida não foi feita, em relação **tornar o usuário líder**, foi discutido se isso é papel de alguma persona no diagrama, já que pensamos que a escolha do líder deve ser por um rank de confiança, onde por cada etapa cumprida o usuário recebe mais pontuação, assim ele pode receber um e-mail sendo chamado para se tornar um líder. Essa linha de pensamento procede, se não, qual seria a melhor forma de tornar um usuário um líder?

**Comment by shayanealcantara** [comment]
> Eu mudei o estilo do diagrama de pacotes para ficar parecido com uma árvore. Eu gostaria de saber se essa mudança é válida e se os componentes desse diagrama de acordo com a futura estrutura do nosso projeto.

@durvalcarvalho, achei bem massa o diagrama, mas validei o diagrama que anexei aqui no comentário https://github.com/fga-eps-mds/2019.2-TimeBolinho/issues/37#issuecomment-531207302 com uma prof e ele parece ser o mais próximo do nosso contexto. Como é um documento estático, pode haver alterações futuramente e já puxando isso, gostei da sua ilustração com n projetos. Apesar disso, o diagrama de pacotes precisa ilustrar a relação e dependência entre os componentes contidos neles (a seta de dependência aberta), o que não foi possível nesse seu diagrama. Eu sugiro tomar como base o diagrama do backend que mandei no comentário com as relações e adicionar outro app, porque isso provavelmente irá ocorrer.

**Comment by KiSobral** [comment]
# Diagrama de Classes

Após me reunir com o @RenatoBrittoAraujo, o diagrama de classes foi atualizado de modo que este se aproxime mais do que será implementado em nossa aplicação.

Atualmente o diagrama não está finalizado, os detalhes sobre cada usuário ainda não foram documentados, mas este já se encontra traduzido e seguindo as convenções de escrita de código Python. 

O diagrama de classes, até então, tomou esta forma: 
![Diagrama_de_Classes_Acacia-1](https://user-images.githubusercontent.com/43852963/65011754-130c5400-d8eb-11e9-9e16-07d461820ebc.png)

___
Não obstante, algumas dúvidas surgiram durante o desenvolvimento do documento. Estas são:

### Dúvidas para a @shayanealcantara 
- A associação entre árvores e propriedades deve se dar por meio de uma associação ou composição? (A dúvida se deve em conta do argumento de que é importante manter os dados de cada árvore armazenados no sistema, logo está deve continuar existindo mesmo se a propriedade for excluída)
- Dado que o usuário vai poder assumir qualquer papel de ator dentro da aplicação (seja este proprietário, líder ou voluntário), faz sentido diferenciar estas classes dentro do diagrama?
- Quais serão os impecilhos em utilizar a API do google de localização? Como isto afetará o diagrama, visto que existem classes específicas para indicar dados de localização?

### Dúvida para a @shayanealcantara e para a @fabiolamfleury 
- Como irá funcionar o gerenciamento de ferramentas de colheita dentro da aplicação?

### Dúvida para a @fabiolamfleury 
- O papel das instituições beneficiárias, dentro da aplicação, ainda ficou vaga para a dupla. O beneficiário entra como um usuário do sistema?

**Comment by fabiolamfleury** [comment]
Pessoal, de usuário vamos usar herança com o User do django, que ele já implementa várias funções:

https://docs.djangoproject.com/en/2.2/ref/contrib/auth/

Ele também da a facilidade de permissões, que podemos usar pra gerenciar nossos tipos diferentes de usuários:

https://docs.djangoproject.com/en/2.2/ref/contrib/auth/#django.contrib.auth.models.Permission

Esse diagrama que vocês fizeram são das models, então coloquem na representação as classes dentro do pacote de models. (Imagem a seguir meramente ilustrativa de o q significa colocar as classes no pacote)

![image](https://user-images.githubusercontent.com/20935369/65066252-6b2e6f00-d95a-11e9-8ba0-0ac785376d17.png)


O diagrama de classes como está, só trabalhando as models, parece um mero reflexo do banco de dados. Ele tem que refletir a arquitetura do nosso projeto, pensando então no django REST e a componentização utilizada em VUE, bem como as relações disso. Sugiro vocês pensarem ao menos as relações no django rest, que além das models, são principais as classes dos Serializers e das Views. Tutorial pra ajudar:

https://www.django-rest-framework.org/tutorial/quickstart/


Em  relação aos beneficiários, acredito que seria melhor deixar ele fora do escopo do projeto. Colocar na colheita um campo, para que seja preenchido pelo líder da colheita, sobre o direcionamento da doação. O que vocês acham?

**Comment by fabiolamfleury** [comment]
@jps12 @durvalcarvalho sugiro vocês juntarem os diagramas de pacotes do front e do back em um diagrama só, mostrando como os dois se relacionam. Apenas uma adição ao que já foi colocado pela a @shayanealcantara

**Comment by flaviovl** [comment]
![Diagrama_Conceitual](https://user-images.githubusercontent.com/31935777/65095021-d8abc100-d995-11e9-8073-d9bebb93858b.png)

**Comment by flaviovl** [comment]
@shayanealcantara  e @vitorcx 

Com base na atualização do diagrama de classe,  fiz essa atualização do diagrama modelo conceitual 

Eu gostaria de saber se essa atualização está no rumo correto?

**Comment by vitorcx** [comment]
@flaviovl Esse novo diagrama trouxe umas ideias interessantes como o tratamento da arvore como entidade e os nomes na língua que usaremos no código, está no rumo certo sim. Tenho algumas observações:
- Acredito que não seja uma boa ideia, no modelo conceitual, representar "picture" como uma entidade, ao meu ver será apenas um tipo de um atributo.  
- Acho que a entidade "leader" seja desnecessária, pois será idêntica à "volunteer", o que pode ser representado pelo autorrelacionamento no qual a entidade possui um atributo que diz qual o papel dela no relacionamento (líder ou voluntario comum), assim como está no diagrama anterior.
- Podem ser aproveitados alguns atributos do diagrama anterior, como o cpf na entidade "proprietario", foto em "arvore"(opcional), e outros que julgar interessantes.

**Comment by durvalcarvalho** [comment]
# Diagrama de Pacotes

O diagrama de pacotes foi modificado diversas vezes durante essa sprint.
Segue algumas das versões que foram feitas e validadas até a versão final.

## Versão 1
Quando essa versão foi feita o grupo de MDS não entendia ao certo o que era e para que servia o diagrama de pacotes. Então foi realizado um simples levantamento da hierarquia dos diretórios e arquivos do backend.

![v0](https://user-images.githubusercontent.com/31013187/65290457-c52f6000-db25-11e9-9bf6-bf22d5aaa8d7.png)

## Versão 2
Essa foi a primeira versão respeitando a simbologia dos diagramas de módulos definidos pela UML. Além de não abordar o frontend da aplicação, alguns erros foram cometidos como a criação de uma pasta templates.

![v1](https://user-images.githubusercontent.com/31013187/65290505-e8f2a600-db25-11e9-959b-d951dc71ddae.jpg)

## Versão 3

Após algumas conversas com a @shayanealcantara, ela auxiliou o grupo de MDS a desenvolver o diagrama de pacotes abordando tanto o frontend e backend, quanto as relações entre os componentes.

![v3](https://user-images.githubusercontent.com/31013187/65290566-3c64f400-db26-11e9-909b-bb3961c643a5.jpg)

@fabiolamfleury @vitorcx @shayanealcantara

**Comment by durvalcarvalho** [comment]
Correções na mensagem dos commits
