### ISSUE TITLE
Internacionalização do produto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#40]
**Descrição**
Eu, como product owner, gostaria de aplicar internalização do produto para poder alcançar mais usuários.

**Critérios de Aceitação** 
- Deverá permitir que a língua no site seja mudada;
- Quando o usuário escolher mudar a língua, essa informação deve ser guardada na sua conta;
- Caso um usuário não logado decida mudar a língua, ainda sim essa informação deve ser guardada no navegador.
- As línguas disponíveis deverão ser: português-BR e inglês.
- No código, os textos devem ser apresentados em inglês, no arquivo de tradução devem ser feitas as partes em português

**Tarefas**
- [x] Buscar e selecionar ferramenta de internalização/localização compatível com vuejs;
- [x] Marcar textos na aplicação para que permitam a tradução;
- [x] Traduzir textos;
- [x] Adicionar botão no site que permita a mudança de língua;
- [x] Disponibilizar as versões de língua de acordo com os critérios de aceitação (salvando as preferências do usuário)

**Observações**

**Comment by KiSobral** [comment]
Para a internacionalização do projeto, foi escolhida a ferramenta do [vue-i18n](https://kazupon.github.io/vue-i18n/).

O vue-i18n é um plugin do vue que cuida das traduções que possam vir a estar disponíveis dentro da aplicação.

**Comment by fabiolamfleury** [comment]
Falta:

Separar as branches do problema da autenticação e essa, e realizar o PR, existe um bug que foi mapeado para issue: #128 


@durvalcarvalho @RenatoBrittoAraujo façam o PR por favor
