### ISSUE TITLE
Cadastro de Usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#43]
**Descrição**
Eu, como usuário, gostaria de me cadastrar no site para obter acesso as funcionalidades.

**Critérios de Aceitação**
- Deverá ter os campos: nome, senha, confirmação de senha, email;
- O campo de nome deve ser preenchido com no mínimo 3 caracteres e no máximo 50;
- A senha deve possuir no mínimo 8 caracteres, e deve coincidir com a confirmação de senha;
- O email deve ter o formato texto@texto.texto
- Deverá possuir validações de campos em todos os níveis: nas models, no endpoint e no frontend;
- A conta do usuário deve estar persistida no banco de dados;
- Funcionalidade testada.

**Tarefas**
- [x] Criação da model de usuário(verificar como herdar do user do django);
- [x] Criação do endpoint de cadastro de usuário;
- [x] Criação da tela do frontend com o formulário de cadastro;
- [x] Validação de campos no frontend
- [x] Envio do formulário do frontend para o backend;
- [x] Resposta de sucesso ou fracasso enviado do backend para o frontend;
- [x] Frontend deve processar a resposta do backend, informando o usuário
- [x] Realizar testes;

**Pareamentos**
- Leonardo e Hugo

**Comment by fabiolamfleury** [comment]
Pontuação de estimativa: 40

**Comment by durvalcarvalho** [comment]
Como sobrescrever o usuário do Django -> [Link](https://www.youtube.com/watch?v=eCeRC7E8Z7Y&list=PLgCYzUzKIBE_dil025VAJnDjNZHHHR9mW&index=12&t=1272s)

Como criar um endpoint para novos usuário -> [Link](https://www.youtube.com/watch?v=_OhF6FEdIao&list=PLgCYzUzKIBE9Pi8wtx8g55fExDAPXBsbV&index=6&t=82s)

**Comment by LeoSilvaGomes** [comment]
> Como sobrescrever o usuário do Django -> [Link](https://www.youtube.com/watch?v=eCeRC7E8Z7Y&list=PLgCYzUzKIBE_dil025VAJnDjNZHHHR9mW&index=12&t=1272s)
> 
> Como criar um endpoint para novos usuário -> [Link](https://www.youtube.com/watch?v=_OhF6FEdIao&list=PLgCYzUzKIBE9Pi8wtx8g55fExDAPXBsbV&index=6&t=82s)

**Comment by durvalcarvalho** [comment]
Endpoint **/users/register/** finalizado.

Para criar um usuário novo pela API basta enviar um POST com o JSON no seguinte formato
```
{
     "email":"acacia@acacia.com",
     "username":"acacia",
     "password2":"acacia_aicaca",
     "password":"acacia_aicaca"
}
```

**Comment by LeoSilvaGomes** [comment]
Foi feito a conexão entre o back e o front. Issa conexão foi feita pelo [axios](https://br.vuejs.org/v2/cookbook/using-axios-to-consume-apis.html), uma biblioteca para consumir api. Além disso foi adicionado um plugin toasted, esse plugin é capaz de mostrar informações(alert) na  tela de forma dinâmica.

**Comment by LeoSilvaGomes** [comment]
Foi adicionado no Back uma biblioteca Djando, [Cors](https://pypi.org/project/django-cors-headers/), essa biblioteca é capaz de manipular as requisições do cabeçalho do server, essa biblioteca foi implementada para seguir algumas politicas de permissões

**Comment by LeoSilvaGomes** [comment]
Planos de resulação da issue:
- [ ] Fazer login automático quando cadastrar
- [ ] Botão e método de Logout
- [ ] Traduzir errors vindo do back
