### ISSUE TITLE
Autenticação de Usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#44]
**Descrição**
Eu, como usuário, gostaria de me autenticar no sistema para manter acesso as funcionalidades.

**Critérios de Aceitação**
- Deverá ter o campo e-mail e senha;
- Deverá manter a sessão do usuário;
- Deverá validar os campos do formulário;
- Deverá permitir o usuário terminar a sessão (log out);
- Funcionalidade testada;

**Tarefas**
- [x] Criar sessão por meio da api;
- [x] Criar formulário no frontend;
- [x] Comunicação de token entre front e back;
- [x] Envio do formulário do frontend para o backend;
- [x] Resposta de sucesso ou fracasso enviado do backend para o frontend;
- [x] Frontend deve processar a resposta do backend, informando o usuário
- [x] Adicionar botão de login;
- [x] Adicionar botão de logout;
- [x] Encerrar sessão por meio da api;
- [x] Testes de api
- [x] Validação de campos do frontend

**Pareamento**

- Renato e Flávio

**Comment by fabiolamfleury** [comment]
Pontuação de estimativa: 20

**Comment by RenatoBrittoAraujo** [comment]
@todomundo Temos que decidir quanto tempo o cookie deveria ser guardado: Eternamente, uma semana, um mês?

**Comment by fabiolamfleury** [comment]
@RenatoBrittoAraujo façam testes em tempo curto para ver se de fato expira e depois pode colocar algo mais eterno

**Comment by durvalcarvalho** [comment]
Playlist explicando como fazer autenticação com o Django Rest [Link](https://www.youtube.com/playlist?list=PLgCYzUzKIBE9Pi8wtx8g55fExDAPXBsbV)

**Comment by fabiolamfleury** [comment]
https://simpleisbetterthancomplex.com/tutorial/2018/12/19/how-to-use-jwt-authentication-with-django-rest-framework.html

**Comment by durvalcarvalho** [comment]
## Autentificação de Usuário

Os endpoints para autentificar o usuário já podem ser usados.

### Criar usuário
Para criar um usuário novo pela API basta enviar um POST com o JSON no seguinte formato
```
{
     "email":"vitas@vitas.com",
     "username":"iAmVitas",
     "password":"vitasIsAwesome",
     "password_confirmation":"vitasIsAwesome"
}
```

### Criar Token de acesso

Para criar um token de acesso, que será usado para acessar os demais endpoints da API, você deve enviar suas credenciais(email e senha) no endpoint **users/token/** , respeitando o seguinte formato:

```
{
     "email":"vitas@vitas.com",
      "password":"vitasIsAwesome",
}
```

Se o seu cadastro existir, você irá receber suas chaves de acesso no seguinte formato
```
{
    "refresh": "eyJ0eXAiOiJKV1Qi...",
    "access": "eyJ0eXAiOiJKV1Qi..."
}
```

### Uso das chaves

Você deve enviar o token _access_ no cabeçalho de suas requisições, para assim obter permissão para acessar os demais endpoints da API

### Renovação dos Tokens

Quando o token _access_ expirar, você deve enviar o token _refresh_ para o endpoint **users/token/refresh/**, no seguinte formato:
```
{
    "refresh": "eyJ0eXAiOiJKV1Qi...",
}
```

Você irá receber um novo token _access_ no seguinte formato
```
{
    "access": "tyy0aXAhOhhKV1Qi...",
}
```

**Comment by RenatoBrittoAraujo** [comment]
@fabiolamfleury Temos um problema, no prototipo não é possível encontrar nenhuma instância de botão de logout, a medida certa agora deve ser criar uma rota de logout e depois pensar em onde adicionar o botão de logout com o resto do time, ou ir contrar o protótipo e adicionar um botão de logout na página home, por exemplo?

**Comment by RenatoBrittoAraujo** [comment]
@fabiolamfleury Todos os requisitos da issue foram atendidos, ela está pronta para ser mergada na develop

**Comment by fabiolamfleury** [comment]
Parte do backend validada e pr aceito, aguardando resposta do time de desenvolvimento quanto ao pr do frontend pra podermos fechar a issue
