### ISSUE TITLE
Configurar integração contínua

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#47]
### Descrição:
Eu, como devops, quero configurar a integração contínua referente ao projeto para automatizar o processo, aumentando sua confiabilidade e rapidez.

### Critérios de aceitação:
- Reduzir o trabalho manual no processo de integração de código.
- A ferramenta deve estar configurada de acordo com as tecnologias do projeto
- A build deve ocorrer em menos de 5 minutos

### Tarefas:
- [x] Definir tecnologias
- [ ] Configurar ambiente
- [ ] Testar configurações

**Comment by shayanealcantara** [comment]
@fabiolamfleury poderia ver/atualizar as tasks dessa issue?

**Comment by shayanealcantara** [comment]
Estarei estudando por meio [deste repositório](https://github.com/repotests/githubpages-tutorial) do devops do meu grupo passado.

**Comment by shayanealcantara** [comment]
[Comparativo travis e gitlab](https://about.gitlab.com/devops-tools/travis-ci-vs-gitlab.html)

**Comment by fabiolamfleury** [comment]
@shayanealcantara atualizei a issue! muito bom ver o travis, mesmo que com o x

**Comment by shayanealcantara** [comment]
Após exploração das ferramentas, descobrimos que o github está com a funcionalidade de [integração contínua](https://github.com/features/actions) diretamente da própria interface, como o gitlab. Sua interface é amigável e com boa documentação. Por esse fato, eu e @vitorcx optamos por usá-la ao invés do travis-ci.
