### ISSUE TITLE
Criar protótipo de alta fidelidade versão mobile

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#50]
**Descrição**
Eu, como desenvolvedor, gostaria de elaborar um protótipo de alta fidelidade para documentar os requisitos e melhor visualizá-los.

**Critérios de Aceitação**
- Deverá possuir páginas de todos os requisitos;
- Os formulários devem ter os campos documentados no doc de arquitetura;
- Deverá respeitar o guia de estilo e identidade visual documentada;
- Deve atentar-se para usabilidade em mobile

**Tarefas**
- [ ] Criar a landing page;
- [x] Criar página de login;
- [x] Criar formulário de cadastro do usuário;
- [x] Criar página de cadastro de propriedade;
- [x] Criar página de cadastro de árvore;
- [x] Criar visualizações de calendário de colheita;
- [x] Criar página de voluntário;
- [x] ...

**Pareamentos**
Os paramentos devem ser utilizados para revisão de telas, uma pessoa faz e o outro revisa, e vice-versa.
- Flávio e Leonardo
- Durval e João
- Hugo e Renato

**Comment by shayanealcantara** [comment]
Algumas ferramentas úteis pra desenvolver o protótipo: 
- [Figma](https://www.figma.com/)
- [Quant UX](https://www.quant-ux.com)
- [Marvel](https://marvelapp.com/)
- ...

**Comment by LeoSilvaGomes** [comment]
Esse comentário visa avaliar cada plataforma de prototipagem e deixar o processo de criação e avaliação mais fácil, para isso foi avaliado algumas caracteristicas dessas plataformas:

- Collaborative design
- External review
- Export prototype
- Icons (Font Awesome)
- Developer Handoff
- Low Complexity
- Animations
- Flow generator
- Variety of tools
- Chart Generator
- Prototype forever

> Todas as caracteristicas citadas são referentes as versões gratuitas das plataformas estudadas

![image](https://user-images.githubusercontent.com/38738836/64915963-e40aac80-d749-11e9-80f4-130511f5bb9f.png)

![image](https://user-images.githubusercontent.com/38738836/64915955-a9087900-d749-11e9-8a2e-1d181eb1e190.png)

Essa plataforma é bem intuitiva e gera uma visualização básica do necessário para nossa aplicação, em geral é boa e compor a estrutura, mas não gera a visualização de gráfico que precisamos e não deixa as pessoas comentarem no erro em específico. Infelizmente não há a possibilidade de baixar as telas. 

- [x] Collaborative design
~- External review~
~- Export prototype~
- [x] Icons (Font Awesome)
~- Developer Handoff~
- [x] Low Complexity
- [x] Animations **Only hover animation**
- [x] Flow generator
~- Variety of tools~
~- Chart Generator~
- [x] Prototype forever

---

![image](https://user-images.githubusercontent.com/38738836/64916195-6c3f8080-d74f-11e9-8a4c-3b63ebbd43c6.png)

Essa plataforma é muito intuitiva e pode gerar visualições  complexas como gráficos, mas não com a qualidade esperada. Infelizmente não pode importar imagem com mais de 1mb,  ou seja, fica impossibilitado de enviar imagens que compõe o projeto com o detalhamento que foi feita

- [x] Collaborative design
- [x] External review
- [x] Export prototype
- [x] Icons (Font Awesome)
~- Developer Handoff~
- [x] Low Complexity
- [x] Animations
- [x] Flow generator
- [x] Variety of tools
- [x] Chart Generator
- [x] Prototype forever

---

![image](https://user-images.githubusercontent.com/38738836/64916229-8fb6fb00-d750-11e9-8900-0a84746b5fb3.png)

![image](https://user-images.githubusercontent.com/38738836/64916223-69915b00-d750-11e9-9590-1e5098a6b133.png)

Essa plataforma é muito boa em geral, para coisas simples e coisas complexas, ela é menos intuitiva que o Studio U, mas nada que não tenha uma curva de aprendizagem pequena, lembra que essa plataforma dentre as três é a que nos dá mais liberdade de componentes tendo vários plugins para a plataforma. **Infelizmente**, a plataforma tem a possibilidade de hovering bem complexa (única parte com media complexidade).

- [x] Collaborative design
- [x] External review
- [x] Export prototype
- [x] Icons (Font Awesome) **Com draft e/ou plugin**
- [x] Developer Handoff
- [x] Low Complexity
- [x] Animations 
- [x] Flow generator
- [x] Variety of tools
- [x] Chart Generator **Com plugin**
~- Prototype forever~

---

![image](https://user-images.githubusercontent.com/38738836/64916233-b2491400-d750-11e9-9ba3-d2169c568e13.png)

Essa plataforma não consegue cumprir o minimo para a gente conseguir fazer o protótipo em grupo de forma gratuita.

**Comment by LeoSilvaGomes** [comment]
A plataforma que será usada para prototipagem será o Figma, foi enviado um e-mail  para todos os colaboradores dessa issue, onde será encaminhado para um protótipo que já tem alguns drafts que iremos utilizar.

Essa plataforma foi escolhida pois contempla uma grande parte das funcionalidades que precisamos para fazer um protótipo, onde podemos colocar exemplos de gráficos, comentar diretamente no erro e trabalhar em uma mesma workbench.

**Comment by LeoSilvaGomes** [comment]
A partir do levantamento de requisitos e analise das possíveis telas, foram designadas telas para cada membro do time de mds, com o intuito de explorar as habilidades de cada um, desde uma página mais simples, até uma mais complexa.

A seguir temos as telas e a respectiva dupla encarregada de faze-la:

- Criar a Landing page: @KiSobral  e @RenatoBrittoAraujo 
- Criar página de login: @durvalcarvalho  e @jps12 
- Criar página cadastro do usuário: @durvalcarvalho  e @jps12 
- Criar páginas de cadastro: @LeoSilvaGomes e @KiSobral
    - Criar página de cadastro de propriedade @flaviovl 
    - Criar página de cadastro de árvore @jps12 
    - Criar página de cadastro de colheita @LeoSilvaGomes 
- Criar página de gerenciar propriedade: @LeoSilvaGomes e @flaviovl 
- Criar Dashboard: @durvalcarvalho  e @jps12 
- Criar Harvest screen: @KiSobral  e @RenatoBrittoAraujo 
     - Criar Harvest screen (Voluntário)
     - Criar Harvest screen (Líder)
     - Criar Harvest screen (Proprietário)
- Criar visualizações de calendário de colheita: @LeoSilvaGomes e @flaviovl

**Comment by LeoSilvaGomes** [comment]
> A plataforma que será usada para prototipagem será o Figma, foi enviado um e-mail para todos os colaboradores dessa issue, onde será encaminhado para um protótipo que já tem alguns drafts que iremos utilizar.
> 
> Essa plataforma foi escolhida pois contempla uma grande parte das funcionalidades que precisamos para fazer um protótipo, onde podemos colocar exemplos de gráficos, comentar diretamente no erro e trabalhar em uma mesma workbench.

Refatoração: O Figma, impossibilita um team editors, e necessariamente precisamos que todos editem no mesmo arquivo, por isso iremos fazer no Quant-Ux.

**Comment by RenatoBrittoAraujo** [comment]
Por landing page pode-se entender a página equivalente a '/about' do usuário logado? @fabiolamfleury

**Comment by LeoSilvaGomes** [comment]
@fabiolamfleury Imagino que têm muitas coisas para colocarmos na página de gerenciar propriedade, irei listar algumas e preciso que você me diga se são condizentes e se falta alguma:

- Editar informações da propriedade
- Editar informações da colheita
- Editar informações da árvore
- Informar estado da colheita (progresso)
- Informar estado da propriedade
- Informar dados da árvore

**Comment by LeoSilvaGomes** [comment]
> Por landing page pode-se entender a página equivalente a '/about' do usuário logado? @fabiolamfleury

![image](https://user-images.githubusercontent.com/38738836/65205367-dadc5100-da63-11e9-9683-e44c82d35856.png)

**Comment by fabiolamfleury** [comment]
https://www.ejplatform.org/home/ esse era o exemplo que eu estava falando para o @LeoSilvaGomes

**Comment by fabiolamfleury** [comment]
Versão validada das telas: https://www.figma.com/proto/s5zHBvcnfzSuNRN7dLpOtD/Telas-Ac%C3%A1cia?node-id=304%3A1274&scaling=min-zoom
