### ISSUE TITLE
Preparar apresentação da Release 1

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#58]
**Descrição**
Eu, como ***time de projeto***, gostaria de ***preparar a apresentação para Release 1*** para ***alinhar visão geral do produto e do projeto***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Apresentação em slides

- A apresentação deve ocupar no máximo 10 minutos

- A apresentação deve priorizar a visão de produto

**Tarefas**
- [x] Criar roteiro da apresentação

- [x] Criar documento powerpoint para apresentação

**Comment by shayanealcantara** [comment]
Criado "esqueleto" inicial do roteiro da apresentação. Está no drive do grupo. Sintam-se libres pra colaborar e alterá-lo :tada:
