### ISSUE TITLE
Cadastrar propriedade

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#66]
**Descrição**
Eu, como ***proprietário***, gostaria de ***cadastrar minha propriedade*** para ***que voluntários possam localizá-la para eventuais colheitas***.

**Depende de:**
- #43 
- #44 

**Critérios de Aceitação**
- Deverá ter os campos: 
  - Tipo de endereço (apartamento, casa, outro),
  - Endereço (aqui vai ser digitado nome da rua/etc. Exemplo: sqs 904)
  - CEP
  - Número
  - Complemento (campo opcional)
  -  Ponto de referência (campo opcional)
  - Cidade 
  - Estado
- Deverá relacionar-se ao proprietário;
- Deverá ter todos os campos validados, apenas os campos destacados como opcionais podem ficar em branco;
- A validação do CEP deve ser feita no modelo brasileiro;
- Deverá possuir validações de campos em todos os níveis: nas models, no endpoint e no frontend;
- A propriedade deve ser persistida no banco de dados;
- O usuário deve estar autenticado para ter acesso a essa página
- Funcionalidade testada.

**Tarefas**
- [x] Criação da model de propriedade(já com a relação ao usuário);
- [x] Criação da tela do frontend com o formulário de cadastro de propriedade;
- [x] Envio do formulário do frontend para o backend;
- [x] Criação do endpoint de cadastro de propriedade;
- [x] Resposta de sucesso ou fracasso enviado do backend para o frontend;
- [x] Frontend deve processar a resposta do backend, informando o usuário
- [x] Realizar testes;
- [ ] Realizar testes no frontend

**Telas do protótipo que devem ser levadas em consideração**
![image](https://user-images.githubusercontent.com/20935369/66274316-af26dc80-e853-11e9-9609-746cd3b3d037.png)

**Comment by fabiolamfleury** [comment]
(o github parece meio bugado e eu não consigo editar a issue, então vou adicionar esse comentário)

A propriedade tem também o atributo de "acesso pelo vizinho" especificado no diagrama de bancos como da colheita

**Comment by durvalcarvalho** [comment]
Biblioteca para validação e consulta de CEP [Link](https://imasters.com.br/back-end/python-consulta-de-cep-com-pycepcorreios)

**Comment by durvalcarvalho** [comment]
Como deve funcionar a validação dos campos dos endereços?

Uma vez que o usuário digitar um CEP válido, é possível obter os dados de outros campos (bairro, cidade, endereço e Estado) utilizando a API dos correios.

Eu estou com a dúvida se esses campos que derivam do CEP devem ser abertos para o usuário editar ou devem ser somente para leitura.

**Comment by fabiolamfleury** [comment]
A validação vai ser apenas se o CEP tem formato válido e se os campos obrigatórios estão preenchidos, devem ser campos abertos para o usuário editar. Não há necessidade de utilizar a API dos correios, apenas o façam se não for prejudicar a entrega da funcionalidade.

**Comment by fabiolamfleury** [comment]
@flaviovl @KiSobral qual é o estado dessa issue?

**Comment by KiSobral** [comment]
> @flaviovl @KiSobral qual é o estado dessa issue?

@fabiolamfleury A visualização do front está com a dependência da criação de um component de select com autocomplete.           
O component tá quase finalizado, com só detalhes de estilização faltando

**Comment by KiSobral** [comment]
Os testes desta issue foram implementados e a estilização está no final.

O component de autocomplete será substituido por um component de select para que a entrega não seja comprometida :)

**Comment by fabiolamfleury** [comment]
A funcionalidade foi aceita nas branches de develop do backend e do frontend, apesar de  não terem testes, para que possa ser feita a relação entre propriedade e árvore na issue #67.

**Comment by fabiolamfleury** [comment]
Faltaram testes de frontend mas o time teve muitas dificuldades para configurações de bibliotecas do vue com o jest, então foi considerada aceita.
