### ISSUE TITLE
Cadastro de Árvore

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#67]
**Descrição**
Eu, como ***proprietário***, gostaria de ***cadastrar árvores*** para ***informar quais são as árvore frutíferas que podem ter seus frutos colhidos na minha propriedade***.

**Depende de:**
- #66 
 
**Critérios de Aceitação**
- Deverá ter os campos: 
  - Altura média,
  - Nome da espécie,
  - Quantidade da árvore na propriedade
  - Época do fruto
  - Quantas vezes ao ano dá fruto 
- Deverá relacionar-se à propriedade;
- Deverá ter todos os campos validados;
- Deverá possuir validações de campos em todos os níveis: nas models, no endpoint e no frontend;
- Uma propriedade pode estar relacionada à várias árvores;
- A árvore deve ser persistida no banco de dados;
- Funcionalidade testada.

**Tarefas**
- [x] Criação da model de árvore(já com a relação à propriedade, lembrando que uma propriedade pode ter várias árvores);
- [x] Criação do endpoint de cadastro de propriedade;
- [x] Criação da tela do frontend com o formulário de cadastro de propriedade;
- [x] Envio do formulário do frontend para o backend;
- [x] Resposta de sucesso ou fracasso enviado do backend para o frontend;
- [x] Frontend deve processar a resposta do backend, informando o usuário
- [x] Realizar testes no backend;
- [x] Relacionar a árvore a uma propriedade

**Telas do protótipo que devem ser levadas em consideração**
![image](https://user-images.githubusercontent.com/20935369/66274498-d54d7c00-e855-11e9-828d-d6e72525dee3.png)

**Comment by durvalcarvalho** [comment]
O que significa essa issue está bloqueada?

![image](https://user-images.githubusercontent.com/31013187/67401176-24e5b480-f585-11e9-88a9-ea81e2c3154d.png)

Eu não posso começar a trabalhar nessa issue enquanto a issue '#66 Cadastrar propriedade' não estiver finalizada?

**Comment by fabiolamfleury** [comment]
Pode, tirei o bloqueio, a implementação vcs vão fazer sem relacionar uma árvore a uma propriedade

**Comment by durvalcarvalho** [comment]
Eu não entendi o _unassigned_... Essa issue é ou não é para eu o @jps12 fazermos?

**Comment by fabiolamfleury** [comment]
O @flaviovl está trabalhando nessa issue e gostaria de trabalhar com um pouco mais de autonomia

**Comment by fabiolamfleury** [comment]
@flaviovl @jps12 não esqueçam de atualizar a branch de vcs com a develop, que agora já tem a lógica de cadastro de propriedade. Não esqueçam de criar a branch aqui no repositório, para acompanharmos melhor o trabalho

**Comment by jps12** [comment]
A página já está mostrando a foto que o usuário carrega. O problema estava que era preciso transformar a imagem que era recebida em uma url. Eu usei uma variável FileReader.
Não tinha notado que não tinhamos dado merge com a develop ainda. Dei merge e tive que resolver alguns conflitos.
