### ISSUE TITLE
Cadastro de Colheita

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#68]
**Descrição**

Eu, como ***proprietário***, gostaria de ***cadastrar uma colheita*** para ***que voluntários possam me auxiliar a realizá-la***.

**Depende de:**
- #67 #74 

**Critérios de Aceitação** 
- Deverá ter os campos:
  - Data
  - Regras (opcional)
  - Descrição (opcional)
  - Status (realizada, não realizada, com voluntário suficientes para realização, aberta para voluntários)
  - Máximo de Voluntários
  - Equipamento necessário (opcional)
- Deverá relacionar-se com árvores (pode ser que uma colheita seja de uma espécie ou mais;
- Deverá possuir validação para os campos;
- A colheita deve ser persistida no banco de dados;
- Funcionalidade testada.
- O usuário deve estar autenticado e possuir uma propriedade para realização dessa funcionalidade.

**Tarefas**
- [x] Criação da model de colheita(já com a relação à(s) árvore(s));
- [x] Criação do endpoint de cadastro de colheita;
- [x] Criação da tela do frontend com o formulário de cadastro de colheita;
- [x] Envio do formulário do frontend para o backend;
- [x]  Resposta de sucesso ou fracasso enviado do backend para o frontend;
- [x]  Frontend deve processar a resposta do backend, informando o usuário
- [x]  Realizar testes;

**Telas do protótipo a serem levadas em consideração**
![image](https://user-images.githubusercontent.com/20935369/66274657-2ad65880-e857-11e9-9e40-18665a24bb73.png)

**Comment by LeoSilvaGomes** [comment]
Foi criado juntamente com @RenatoBrittoAraujo a parte estrutural do Backend do página de colheita.

Adicionamos as funcionalidades necessárias e essenciais para fazer o CRUD, agregando os campos  date, description, status, max_volunteers, equipment, neighbor_access. Tiramos embasamento desses campos a partir das discussões levantadas e pelo documento de arquitetura, especialmente pelo diagrama de classes, que nos dá uma visão ampla dos campos. 

Para as rules pensamos em fazer uma classe separada que tem um vinculo com uma propriedade, a partir de uma Foreign Key, assim, para o banco de dados, o tratamento dessa variável se torna melhor e mais claro. Entretanto ainda estamos no caminho de estudos para saber como é a melhor forma de utilizar essa estratégia. (Essa parte foi mentorada pelo @durvalcarvalho).  

O que falta:
- [ ] Criar teste
- [ ] Pensar na manipulação das regras

**Comment by RenatoBrittoAraujo** [comment]
@fabiolamfleury Sobre o que a issue pede de campos para o registro, você pode dar clarificações a respeito disso:
> Status (realizada, não realizada, com voluntário suficientes para realização, aberta para voluntários)

Eu e @LeoSilvaGomes não entendemos o porque do usuário poder colocar o status da sua própria colheita se:
1. Todos os status descritos podem ser calculados de forma automatizada.
2. Um usuário pode criar uma colheita que já foi realizada?

Entre outras divagações sobre esse campo de input.

**Comment by fabiolamfleury** [comment]
@RenatoBrittoAraujo esse é um campo que deverá existir na model, ele não vai ser alterado pelo usuário. Como default, vocês ao criarem vão colocar ela como aberta para voluntários na criação.

**Comment by LeoSilvaGomes** [comment]
![image](https://user-images.githubusercontent.com/38738836/67511998-4c647c00-f66e-11e9-9eb4-f247004c9a08.png)

![image](https://user-images.githubusercontent.com/38738836/67512027-5dad8880-f66e-11e9-8992-0b4531533ebf.png)

Terminamos a model e conseguimos entender como funcionará a relação das rules com a model Harvest a partir de um Foreign Key, fizemos a funcionalidade de dar um create da rules com a model da harvest, onde criamos o serializer de cada um e integramos a rules no harvest com to-many relation, especificando **many=True**, **write_only=True**, que nos possibilita fazer essa relação.

Além disso fizemos a implementação do Front, ainda sem validate e sem os test, precisamos integrar um listfield no front para as regras.

- [ ] Test Front
- [ ] Test Back
- [ ] Validate
- [ ] ListField (component)

**Comment by LeoSilvaGomes** [comment]
Conseguimos concluir as funcionalidades que foram pedidas, implementamos muitos componentes a partir de uma biblioteca vue chamada [vuetify](https://vuetifyjs.com/pt-BR/), que nos ajuda na criação dessas estruturas um tanto complexas.

![image](https://user-images.githubusercontent.com/38738836/67619484-a8e0ac00-f7d2-11e9-8a1c-7a209f1f5ac1.png)
