### ISSUE TITLE
Visualização de Colheitas

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#69]
**Descrição**
Eu, como ***voluntário***, gostaria de ***visualizar colheitas*** para ***que possa decidir voluntariar-me para realizá-la***.

**Depende de:**
#68 

**Critérios de Aceitação**
- Deverá permitir a visualização da **data**, **bairro/cidade**, **número de voluntários necessários** e **status** da colheita.;
- Essa visualização deve ser permitida para usuários autenticados ou não;
- A visualização deve estar de acordo com o protótipo de alta fidelidade;
- Deve haver ênfase em colheitas que ainda não foram realizadas
- Funcionalidade testada;

**Tarefas**
- [x] Criação do endpoint que exibe todas as colheitas cadastras, exibindo apenas os campos: data, bairro/cidade, número de voluntários, e status da colheita;
- [ ] Criar endpoint com filtros por status da colheita;
- [x] Criar endpoint com filtros por data, apenas as que estão na semana atual;
- [ ] Criar endpoint com filtro por data, apenas as que estão no mês atual;
- [x] Criação da tela com visualização de colheitas no frontend;
- [x] Exibição dos dados do endpoint no frontend.
- [x] Realização de testes

**Telas do protótipo a serem levadas em consideração**

![66274821-adabe300-e858-11e9-9fb4-1634d1c9236b(1)](https://user-images.githubusercontent.com/33501171/68533672-7377aa80-030a-11ea-92c0-840289da1454.png)

**Comment by durvalcarvalho** [comment]
A rota harvests irá retornar todas as colheitas criada nos últimos 7 dias
http://localhost:8000/harvests/
```
path(
        'harvests/',
        WeekHarvests.as_view({'get': 'list'})
    ),
```

**Comment by durvalcarvalho** [comment]
Invés de criar 3 rotas, uma para todas as colheitas, outra para a do mês e outra para a da semana, poderiamos criar uma rota dinámica que cria diferentes queries de acordo com o parâmetro passado na url.

Ficaria algo do tipo
```
path(
        'harvests/<int:timedelta>/',
        WeekHarvests.as_view({'get': 'list'})
    ),
```
