### ISSUE TITLE
Atualizar Perfil do Usuário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#73]
**Descrição**
Eu, como ***usuário***, gostaria de ***atualizar meu perfil*** para ***refletir melhor minha participação na comunidade***.

**Depende de:**

#43 #44 

**Critérios de Aceitação**
- Deverá ter os campos:
   - Data de nascimento
   - Email
  - Telefone
  - Bio
  - Username
  - Foto de perfil
 - Quais atribuições o usuário quer realizar na plataforma (proprietário, líder de colheita, colheita, pode ser mais de um, é apenas o que ele almeja)
- O usuário deverá estar autenticado para acessar a página;
- Todos os campos deverão estar validados e serem opcionais (tirando os campos do cadastro);

**Tarefas**
- [x] Criar página de edição do perfil;
- [x] Criar endpoint que provê as informações do perfil do usuário autenticado;
- [x] Carregar, na página de edição de perfil, as informações atuais do perfil do usuário;
- [x] Exibir formulário com as informações atuais, permitindo a edição;
- [x] Salvar as informações atualizadas e validadas;

**Comment by durvalcarvalho** [comment]
No backend foi modificado o serializer da model Profile. Foi adicionado os campos username e email, que fazem referência aos campos de mesmo nome da model User.

Eu estou com dificuldade de validar se os dados recebidos nesse campo são validos e atualizar tanto o profile quanto o user.

**Comment by jps12** [comment]
Os dados estavam sendo recebidos pelo front corretamente, mas faltava os campos de username e email que pertencem a classe user dentro do back. Agora a funcionalidade get está dando erro por esse motivo.

**Comment by jps12** [comment]
A data de nascimento já está sendo alterada corretamente no formato que está no backend. Em resumo as funcionalidade que faltam em nível de front são: 
- Comunicação back-front
- Correções na parte visual da página.

**Comment by durvalcarvalho** [comment]
> No backend foi modificado o serializer da model Profile. Foi adicionado os campos username e email, que fazem referência aos campos de mesmo nome da model User.
> 
> Eu estou com dificuldade de validar se os dados recebidos nesse campo são validos e atualizar tanto o profile quanto o user.

Resolvido

**Comment by jps12** [comment]
Todos os dados estão sendo mostrados na tela. Agora só falta mandar os dados alterados para o backend.
