### ISSUE TITLE
Visualizações do Calendário

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#74]
**Descrição**
Eu, como ***usuário***, gostaria de ***ver informações gerais da plataforma*** para ***entender quais atividades serão/foram realizadas***.

**Critérios de Aceitação** 
- A tela deve ser exibida para usuários autenticados ou não;
- Deve-se implementar também a visualização de calendário, mesmo que ainda sem as colheitas (usar dados estáticos para visualização de colheitas);
- Deve haver uma diferenciação para atividades que já ocorreram ou não

**Tarefas**
- [x] Capturar, utilizando o vue, qual é a data atual;
- [x] Criar a visualização de calendário por mês;
- [x] Criar uma diferenciação, para que as datas do passado sejam visualizadas de forma diferente do presente/futuro;

**Telas do protótipo a serem levadas em consideração**
![image](https://user-images.githubusercontent.com/20935369/66274369-59066900-e854-11e9-83bf-445b7d55fe25.png)

**Comment by durvalcarvalho** [comment]
Componente que podemos usar nessa issue 
https://vcalendar.io/guide/

**Comment by LeoSilvaGomes** [comment]
![image](https://user-images.githubusercontent.com/38738836/68074499-58d98a80-fd7a-11e9-8e2e-95f7c0dfc0dd.png)

![image](https://user-images.githubusercontent.com/38738836/68074502-64c54c80-fd7a-11e9-807f-28e51443709e.png)

Utilizamos a biblioteca acima para as funcionalidades do calendário, entretanto estilizamos de uma forma um pouco diferente, fizemos nossas classes e alteramos configurações das classes já existentes, todas as outras coisas que estão nessas foram implementas pela dupla sem a necessidade fazer um componente.

Fizemos todas as estruturas para receber as informações do back
