### ISSUE TITLE
Landing page simplificada

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#75]
**Descrição**
Eu, como ***usuário***, gostaria de ***visualizar dados sobre a plataforma*** para ***me sentir pertencente à comunidade e sentir que faço parte de algo que muda o mundo***.

TEXTO MOTIVACIONAL: Acácia propõe-se a facilitar a criação de uma comunidade voluntária em torno da agricultura urbana, diminuindo o desperdício de comida e difundindo conhecimento em plantio e colheita neste ambiente. Crie já sua conta e participe desta mudança!

**Depende de:**

#69 #71 

**Critérios de Aceitação**
- [x] Página inicial simplificada
- [x] Possuir um texto motivador para usar a acácia
- [x] Na parte de baixo da tela, não precisa de tudo que tem na imagem, apenas o link do github

Referência

![image](https://user-images.githubusercontent.com/20935369/68076138-aca29e80-fd8f-11e9-897f-9e1f4cc5df21.png)

**Comment by jps12** [comment]
A landing page vai ser a página raiz da aplicação?

**Comment by shayanealcantara** [comment]
Isso, é nessa ideia mesmo. Inclusive, pensei aqui e não sei se os botões de cadastro e login entram nessa página. Faz sentido entrar, mas não sei como a @fabiolamfleury quer. Vocês pensaram algo a respeito? Porque pelo texto motivacional, tem um convite pra criar a conta, pelo menos.

**Comment by jps12** [comment]
Então @shayanealcantara  já tem o botão de cadastro na sidebar que está presente na landing page então é necessário a criação de mais um botão?

**Comment by shayanealcantara** [comment]
> Então @shayanealcantara já tem o botão de cadastro na sidebar que está presente na landing page então é necessário a criação de mais um botão?

Então, acho que fica legal. **MAS**, avaliem o esforço que isso teria e avilem também se a experiência do usuário seria comprometida caso não haja botões.

**Comment by LeoSilvaGomes** [comment]
![image](https://user-images.githubusercontent.com/38738836/68352427-2961af80-00e5-11ea-82e2-ab5be1ed0dda.png)

![image](https://user-images.githubusercontent.com/38738836/68352438-3088bd80-00e5-11ea-8803-9596290e6ba6.png)

Landing page está concluída, não  precisou mais que um dia para ser concluída, utilizamos nenhum biblioteca e fizemos apenas o componente BottomBar, no qual foi pedido na issue. Em geral não foi feito mais que o pedido nem menos

**Comment by fabiolamfleury** [comment]
@LeoSilvaGomes @jps12 a ideia é essa página ser renderizada no '/' quando o usuário não estiver logado. Caso ele esteja logado, ao tentar acessar o '/' ele deve ser redirecionado para a rota '/dashboard'. É bem tranquilo, se vcs derem uma olhada no router do vue já tem funções parecidas, se tiverem dúvida falem cmg

**Comment by LeoSilvaGomes** [comment]
> @fabiolamfleury Tudo bem, irei ajustar isso agora, mas então quando o usuário logar, ele deve ir para o dashboard certo? porque se for isso eu já mudo as rotas aqui

Porque até o momento quando o usuário faz o login, ele é encaminhado para o '/'

**Comment by fabiolamfleury** [comment]
> ra, mas então quando o usuário logar, ele deve ir para o dashboard certo? porque se for isso eu já mudo as rotas aqui

Sim :)
