### ISSUE TITLE
Configurar ambiente de homologação

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#79]
**Descrição**
Eu, como ***devops***, gostaria de ***configurar ambiente de homologação*** para ***ter um ambiente de validação de funções e da aplicação em sua totalidade***.

**Critérios de Aceitação**
- Deverá disponibilizar em um endereço o ambiente de homologação, do estado atual da dev do backend;
- Deverá disponibilizar em um endereço o ambiente de homologação, do estado atual da dev do frontend;

**Tarefas**
- [x] Escolher a ferramenta para hospedagem;
- [x] Estimar a capacidade computacional necessária (máquinas) para ;
- [x] Hospedar a aplicação, presente na dev, na ferramenta de deploy;

**Comment by vitorcx** [comment]
Foi feito o deploy do frontend no heroku, a partir deste [fork](https://github.com/vitorcx/2019.2-Acacia-Frontend), como teste. Está acessível neste [link](https://acacia-staging-test.herokuapp.com). O deploy do backend não foi completo.

**Comment by vitorcx** [comment]
Eu e a @shayanealcantara conseguimos fazer o deploy do backend no heroku, a partir deste [fork](https://github.com/vitorcx/2019.2-Acacia), como teste. Está acessível neste [link](https://acacia-backend-staging-test.herokuapp.com). Pra finalizar a issue serão configuradas as variáveis do ambiente de homologação necessárias e o deploy de cara repositório no heroku.

**Comment by shayanealcantara** [comment]
Essas são as informações que temos sobre a capacidade da hospedagem 0800 do heroku 
<img src="https://user-images.githubusercontent.com/33501171/67145865-90fdab00-f25b-11e9-8436-8a90f1ecfbab.png" width=200>
<img src="https://user-images.githubusercontent.com/33501171/67145866-922ed800-f25b-11e9-90cd-f1d7476fd926.png" width=200>

**Comment by fabiolamfleury** [comment]
Os ambientes do frontend e do backend, separadamente, estão funcionando no ambiente de homologação do heroku, a issue foi considerada entregue e foi aberta uma [issue](#123) para comunicação entre os dois ambientes
