### ISSUE TITLE
Configurar ambiente de produção

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#80]
**Descrição**
Eu, como ***devops***, gostaria de ***configurar o ambiente de produção*** para ***disponibilizar de forma estável o produto***.

**Depende de:**

#79

**Critérios de Aceitação**
- Deverá ter o campo ...;
- Deverá calcular/apresentar ...;
- Funcionalidade testada;

**Tarefas**
- [ ] Não é um épico. [Leia](https://sitecampus.com.br/user-story-epico-e-tema-qual-diferenca/);
- [ ] É testável;
- [ ] É estimável pelo time de desenvolvimento;
- [ ] Traz valor ao negócio;

**Observações**

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by shayanealcantara** [comment]
Ambiente de produção no frontend não está funcionando.

**Comment by shayanealcantara** [comment]
Outra issue será criada para resolver as tarefas do frontend.
