### ISSUE TITLE
Configurar entrega contínua

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#81]
**Descrição**
Eu, como ***devops***, gostaria de ***configurar a entrega contínua*** para ***automatizar a entrega do produto***.

**Critérios de Aceitação** 
- Pushs na branch master ativando o workflow de deploy do ambiente de produção

**Tarefas**
- [x] Configurar workflow do github actions

**Observações**

- Essa issue depende da configuração do ambiente de produção para ser validada por completo

**Comment by vitorcx** [comment]
Houve um problema na conexão com a instância do postgres no heroku que atrapalhou o andamento das issues #158 #81 #80

**Comment by vitorcx** [comment]
> Houve um problema na conexão com a instância do postgres no heroku que atrapalhou o andamento das issues #158 #81 #80

O heroku não será mais usado, o deploy será feito na digital ocean

**Comment by shayanealcantara** [comment]
Devido ao heroku depender de muitas configurações, e visto também que não estava sendo possível resolver os problemas do postgres nele, decidimos trocar a hospedagem para não atrasar as issues demandadas. Agora os ambientes de homologação e produção estão estáveis com a máquina hospedada. 
Segue os links: 
Homo.: `45.55.46.19:8080` 
Prod.: `45.55.46.19:8081`
