### ISSUE TITLE
Definir processo do projeto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#9]
### Descrição

Definir como o time vai trabalhar usando Scrum e eXtreme Programming

### Critérios de aceitação:

- [x] Número de reuniões diárias e tempo necessário

- [x] Dia de início e fim, e duração das sprints

- [x] Dias e duração das reuniões

- [x] Como vai funcionar a comunicação?

### Tarefas:

- [x]  Criar documentos no github pages

- [x] Apresentar documento para a equipe

**Comment by MarthaDs** [comment]
Foi feito um estudo sobre a viabilidade de aliar tecnicas de gamificação ao processo do projeto, visando vivelar o ritmo da equipe de desenvolvimento e manter sua produvidade continua e saudável.

#### Referência

Tommaso Dal Sasso, Andrea Mocci, Michele Lanza, Ebrisa Mastrodicasa
REVEAL @ Faculty of Informatics — University of Lugano, Switzerland.Disponível em:
https://www.dalsat.me/download/publications/saner2017.pdf

**Comment by MarthaDs** [comment]
Foi feito um estudo para definir o time-box das sprints do projeto.

Referência
Disponível em : https://www.scrumguides.org/scrum-guide.html
