### ISSUE TITLE
Criar a Release

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#90]
**Descrição**
Eu, como ***devops***, gostaria de ***criar uma release*** para ***realizar uma entrega parcial do produto***.

**Critérios de Aceitação**
- Deverá resumir o trabalho realizado e entregue nas branches: master e gh-pages;

**Tarefas**
- [x] Criar release no github;
- [x] Criar lista explicando o que foi entregue;

**Comment by shayanealcantara** [comment]
Estamos em dúvida se a release tem que ter só coisas do software de valor pro usuário (funcionalidades/bugfix...) ou tem que ter tudo, inclusive a documentação que fizemos.
