### ISSUE TITLE
Refatorar requisitos no documento de visão

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-Acacia#93]
**Descrição**
Eu, como ***time de desenvolvimento***, gostaria de ***refatorar os requisitos*** para ***alinhar os requisitos levantados pela product owner***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Deverá ter o alinhamento dos requisitos de acordo com as histórias de usuários criadas.
- Deverá ser documentado e atualizado no github pages
- Diferenciar requisitos funcionais (histórias de usuário) e requisitos não funcionais (histórias técnicas)
- Os requisitos devem ser sua prioridade e dependências mapeadas
- Os requisitos devem ter rastreabilidade entre o documento de arquitetura e o documento de visão

**Tarefas**
- [x] Documentar os requisitos atualizados no github pages

**Comment by fabiolamfleury** [comment]
Não existe um rastreamento correto de requisitos entre o documento de visão e o documento de arquitetura, isso deve ser corrigido

**Comment by fabiolamfleury** [comment]
História repontuada de acordo com a carga de trabalha que falta para completá-la
